In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.model_selection import GridSearchCV
from sklearn import metrics
import scipy.stats as stat
import pylab 
import math
from sklearn.neighbors import KNeighborsClassifier as knn
from sklearn.linear_model import LogisticRegression as LGR,Lasso
from sklearn.ensemble import RandomForestClassifier as rfc
from sklearn.feature_selection import SelectFromModel
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import StratifiedKFold

In [12]:
Fe_CAAC_dataset = df = pd.read_excel("F:\\Nitrogen_activation\\rajaraman\\office\\ofifice\\jupyter\\Extension\\T07\\heatmap\\agostic\\LR_F03\\N2_activation_extension_T07_heatmap_agostaic_descrptors.xlsx")

In [13]:
df_1=df.drop(['F00','T01','T02','T03',],axis=1)
df_2=df_1.drop([0,18,9])
df_3=df_1.drop([0,18,9,8,26,17])
df_4=df_1.drop([8,26,17])

# F03

In [14]:
#X = df.drop(['F01','F04','F05','F06','F07','F08','F09','F10','F11','F12','F13','F14','F15','T01','T02','T03','T04','T05'],axis=1)
#X = df_3.drop(['F01','F02','F19','F08','F03','F14','F07','F15','F17','F18','F09','F16','F11','F05','F04','T01','T07','T03','T04','T05','F03','T06','T08','T02',],axis=1)

#'F13','F10','F12','F09','F16','F11','F05','F04'

X = df_3.drop(['T04','F01','F02','F04','F06','F04','F05','F08','F09','F07','F10',],axis=1)
y = df_3['T04']# loading the linear regression model


X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20, random_state=20)

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
scaler = MinMaxScaler()
# fit the scaler to the train set, it will learn the parameters
scaler.fit(X_train)
# transform train and test sets
X_train_scaled_MM = scaler.transform(X_train)
X_test_scaled_MM = scaler.transform(X_test)
X_train_scaled_MM = pd.DataFrame(X_train_scaled_MM, columns=X_train.columns)
X_test_scaled_MM = pd.DataFrame(X_test_scaled_MM, columns=X_test.columns)

#LinearRegression_scaling
lin_reg_model = LinearRegression()
lin_reg_model.fit(X_train_scaled_MM,y_train)
# prediction on Training data
training_data_prediction_X_train_lin_reg = lin_reg_model.predict(X_train_scaled_MM)
# prediction on Test data
test_data_prediction_X_test_lin_reg = lin_reg_model.predict(X_test_scaled_MM)


# R squared Error
error_score_r2 = metrics.r2_score(y_train, training_data_prediction_X_train_lin_reg)
error_score_MAE = metrics.mean_absolute_error(y_train, training_data_prediction_X_train_lin_reg)
print("R squared Error : ", error_score_r2)
print("mean_absolute_error : ", error_score_MAE)
# R squared Error
error_score_r2 = metrics.r2_score(y_test, test_data_prediction_X_test_lin_reg)
error_score_MAE = metrics.mean_absolute_error(y_test, test_data_prediction_X_test_lin_reg)
print("R squared Error : ", error_score_r2)
print("mean_absolute_error : ", error_score_MAE)

coeff = lin_reg_model.coef_
features = X.columns
df_coeff = pd.DataFrame({"features":features,"coeff":coeff})
df_coeff.sort_values("coeff")

R squared Error :  0.8389442557346501
mean_absolute_error :  13.24576166674602
R squared Error :  0.7600673944067398
mean_absolute_error :  9.251587677217449


features       coeff
0      F03 -102.394536

In [15]:
X = df_3.drop(['T04','F01','F02','F04','F06','F04','F05','F08','F09','F07','F10',],axis=1)
y = df_3['T04']# loading the linear regression model


X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20, random_state=20)

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
scaler = MinMaxScaler()
# fit the scaler to the train set, it will learn the parameters
scaler.fit(X_train)
# transform train and test sets
X_train_scaled_MM = scaler.transform(X_train)
X_test_scaled_MM = scaler.transform(X_test)
X_train_scaled_MM = pd.DataFrame(X_train_scaled_MM, columns=X_train.columns)
X_test_scaled_MM = pd.DataFrame(X_test_scaled_MM, columns=X_test.columns)

# Ensure y_train indices match X_train_scaled_MM
y_train = y_train.reset_index(drop=True)
X_train_scaled_MM = X_train_scaled_MM.reset_index(drop=True)
print(X_train_scaled_MM.index.equals(y_train.index))  # Should print True

import statsmodels.api as sm
X_sm = sm.add_constant(X_train_scaled_MM)
model = sm.OLS(y_train,X_sm).fit()
model.summary()

True


c:\users\nettemchandra sekhar\appdata\local\programs\python\python39\lib\site-packages\scipy\stats\_stats_py.py:1769: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=16
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    T04   R-squared:                       0.839
Model:                            OLS   Adj. R-squared:                  0.827
Method:                 Least Squares   F-statistic:                     72.93
Date:                Thu, 05 Sep 2024   Prob (F-statistic):           6.35e-07
Time:                        09:27:40   Log-Likelihood:                -67.828
No. Observations:                  16   AIC:                             139.7
Df Residuals:                      14   BIC:                             141.2
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        147.7314      7.541     19.590      0.000     131.557     163.905
F03         -102.3945     11.990     -8.540      0.000    -128.111     -76.678
==============================================================================
Omnibus:                        5.007   Durbin-Watson:                   2.799
Prob(Omnibus):                  0.082   Jarque-Bera (JB):                2.644
Skew:                          -0.950   Prob(JB):                        0.267
Kurtosis:                       3.594   Cond. No.                         3.44
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [16]:
# can tune other metrics, such as MSE
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
scaler = MinMaxScaler()
# fit the scaler to the train set, it will learn the parameters
scaler.fit(X)
# transform train and test sets
X_scaled_MM = scaler.transform(X)
X_scaled_MM = pd.DataFrame(X_scaled_MM, columns=X.columns)

scores = cross_val_score(lin_reg_model, X_scaled_MM, y, cv=2)
print(scores)
print(np.mean(scores))

scores = cross_val_score(lin_reg_model, X_scaled_MM, y, cv=3)
print(scores)
print(np.mean(scores))

scores = cross_val_score(lin_reg_model, X_scaled_MM, y, cv=4)
print(scores)
print(np.mean(scores))

scores = cross_val_score(lin_reg_model, X_scaled_MM, y, cv=5)
print(scores)
print(np.mean(scores))


[0.80816419 0.80650019]
0.8073321913535885
[0.84303049 0.78036005 0.79377145]
0.8057206638747795
[0.71900905 0.80113348 0.87197762 0.71691909]
0.7772598097365238
[0.57486123 0.85076537 0.69763965 0.89502875 0.56955395]
0.7175697923695774


In [17]:

# Initialize the Leave-One-Out cross-validator
loo = LeaveOneOut()

# Drop the specified columns and set target variable
X = df_3.drop(['T04','F01','F02','F04','F06','F04','F05','F08','F09','F07','F10',],axis=1)
y = df_3['T04']# loading the linear regression model

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
# Apply MinMax Scaling
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)  # Scale the features and store them in X_scaled


# Initialize lists to store predictions and actual values
y_pred_loo = []
y_true_loo = []

# Loop over each training/test split
for train_index, test_index in loo.split(X_scaled):
    X_train_loo, X_test_loo = X_scaled[train_index], X_scaled[test_index]
    y_train_loo, y_test_loo = y.iloc[train_index], y.iloc[test_index]
    
    # Train the Lasso model
    linear_reg_model = LinearRegression()
    linear_reg_model.fit(X_train_loo, y_train_loo)
    
    # Predict the left-out sample
    y_pred_loo.append(linear_reg_model.predict(X_test_loo)[0])
    y_true_loo.append(y_test_loo.values[0])

# Convert lists to arrays
y_pred_loo = np.array(y_pred_loo)
y_true_loo = np.array(y_true_loo)

# Calculate LOO performance metrics
Q2_loo = r2_score(y_true_loo, y_pred_loo)
MAE_loo = mean_absolute_error(y_true_loo, y_pred_loo)
MSE_loo = mean_squared_error(y_true_loo, y_pred_loo)
RMSE_loo = np.sqrt(MSE_loo)

# Print the results
print("LOO Q^2 score: ", Q2_loo)
print("LOO Mean Absolute Error: ", MAE_loo)
print("LOO Mean Squared Error: ", MSE_loo)
print("LOO Root Mean Squared Error: ", RMSE_loo)



LOO Q^2 score:  0.7973225093932432
LOO Mean Absolute Error:  13.38829820748417
LOO Mean Squared Error:  304.19396071505554
LOO Root Mean Squared Error:  17.441157092207373
