In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.model_selection import GridSearchCV
from sklearn import metrics
import scipy.stats as stat
import pylab 
import math
from sklearn.neighbors import KNeighborsClassifier as knn
from sklearn.linear_model import LogisticRegression as LGR,Lasso
from sklearn.ensemble import RandomForestClassifier as rfc
from sklearn.feature_selection import SelectFromModel
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import StratifiedKFold

In [16]:
Fe_CAAC_dataset = df = pd.read_excel("F:\\Nitrogen_activation\\rajaraman\\office\\ofifice\\jupyter\\Extension\\T07\\heatmap\\agostic\\LR_F05_F06\\N2_activation_extension_T07_heatmap_agostaic_descrptors.xlsx")

In [17]:
df_1=df.drop(['F00','T01','T02','T03',],axis=1)
df_2=df_1.drop([0,18,9])
df_3=df_1.drop([0,18,9,8,26,17])
df_4=df_1.drop([8,26,17])

In [18]:
df_3

F01  F02      F03    F04    F05     F06  F07      F08       F09  \
1   163.20    0  2.16440  57.66  4.000 -0.5780    4 -0.26690  3.129162   
2   156.45    0  2.11500  60.54  4.935 -0.5930    5 -0.27940  3.079298   
3   179.11    1  2.11830  60.55  5.935 -0.5750    6 -0.27220  3.099190   
4   166.05    0  1.98800  63.35  2.988 -0.5610    7 -0.45250  3.038704   
5   166.70    0  1.95700  64.71  1.996 -0.5907    8 -0.45890  3.006000   
6   169.01    0  1.90100  66.20  1.013 -0.6190    9 -0.41270  2.989176   
7   167.20    0  1.87235  68.11  0.000 -0.6450   10 -0.31450  2.936456   
10  162.65    0  2.16400  57.41  3.961 -0.5860    4 -0.26890  3.185635   
11  154.68    0  2.11100  60.24  4.938 -0.6020    5 -0.27420  3.150027   
12  168.44    1  2.09600  60.38  3.973 -0.5900    6 -0.27320  3.163894   
13  165.32    0  1.98500  62.78  2.989 -0.5710    7 -0.46920  3.163894   
14  166.00    0  1.95500  64.27  1.995 -0.5990    8 -0.45830  3.068475   
15  169.13    0  1.89600  65.73  1.011 -0.6320    9 -0.41640  3.056635   
16  167.15    0  1.86700  68.07  0.000 -0.6450   10 -0.31700  2.987179   
19  154.91    0  2.16380  57.41  3.960 -0.5810    4 -0.26710  3.088027   
20  156.57    0  2.12200  60.24  4.930 -0.5580    5 -0.28400  3.047360   
21  176.40    1  2.12550  62.00  5.934 -0.5800    6 -0.27320  3.112600   
22  167.94    0  1.99500  67.44  3.001 -0.5790    7 -0.46500  3.007413   
23  169.34    0  1.98200  68.92  2.019 -0.6050    8 -0.45095  2.974494   
24  170.33    0  1.90405  70.13  1.019 -0.6270    9 -0.42190  2.987691   
25  167.99    0  1.87900  70.26  0.000 -0.6360   10 -0.31970  2.935756   

        F10         T04  
1   -83.337   25.243201  
2   -62.179   80.539565  
3  -178.369   63.400511  
4   -69.285   97.057793  
5   -76.022   94.337618  
6   -73.799  126.165031  
7  -166.152  158.160792  
10  -87.602   54.848496  
11 -179.951   84.663254  
12  -76.949   77.707753  
13  -68.184  111.384753  
14  -80.499   96.725090  
15  -75.569  134.989547  
16  177.099  172.156151  
19  -81.440   48.921745  
20  177.766   70.614886  
21  -74.263   56.669963  
22  -72.120   60.127639  
23  -78.089  111.601462  
24  -77.043  134.842989  
25 -152.612  153.204294

# F05_F06

In [21]:
#X = df.drop(['F01','F04','F05','F06','F07','F08','F09','F10','F11','F12','F13','F14','F15','T01','T02','T03','T04','T05'],axis=1)
#X = df_3.drop(['F01','F02','F19','F08','F03','F14','F07','F15','F17','F18','F09','F16','F11','F05','F04','T01','T07','T03','T04','T05','F03','T06','T08','T02',],axis=1)

#'F13','F10','F12','F09','F16','F11','F05','F04'

X = df_3.drop(['T04','F01','F02','F03','F04','F08','F09','F07','F10',],axis=1)
y = df_3['T04']# loading the linear regression model



X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20, random_state=20)

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
scaler = MinMaxScaler()
# fit the scaler to the train set, it will learn the parameters
scaler.fit(X_train)
# transform train and test sets
X_train_scaled_MM = scaler.transform(X_train)
X_test_scaled_MM = scaler.transform(X_test)
X_train_scaled_MM = pd.DataFrame(X_train_scaled_MM, columns=X_train.columns)
X_test_scaled_MM = pd.DataFrame(X_test_scaled_MM, columns=X_test.columns)

#LinearRegression_scaling
lin_reg_model = LinearRegression()
lin_reg_model.fit(X_train_scaled_MM,y_train)
# prediction on Training data
training_data_prediction_X_train_lin_reg = lin_reg_model.predict(X_train_scaled_MM)
# prediction on Test data
test_data_prediction_X_test_lin_reg = lin_reg_model.predict(X_test_scaled_MM)


# R squared Error
error_score_r2 = metrics.r2_score(y_train, training_data_prediction_X_train_lin_reg)
error_score_MAE = metrics.mean_absolute_error(y_train, training_data_prediction_X_train_lin_reg)
print("R squared Error : ", error_score_r2)
print("mean_absolute_error : ", error_score_MAE)
# R squared Error
error_score_r2 = metrics.r2_score(y_test, test_data_prediction_X_test_lin_reg)
error_score_MAE = metrics.mean_absolute_error(y_test, test_data_prediction_X_test_lin_reg)
print("R squared Error : ", error_score_r2)
print("mean_absolute_error : ", error_score_MAE)

coeff = lin_reg_model.coef_
features = X.columns
df_coeff = pd.DataFrame({"features":features,"coeff":coeff})
df_coeff.sort_values("coeff")

R squared Error :  0.7674785132116272
mean_absolute_error :  16.18956641775148
R squared Error :  0.8766889320855895
mean_absolute_error :  7.623083830244286


features      coeff
0      F05 -79.293359
1      F06 -40.820176

In [20]:
X = df_3.drop(['T04','F01','F02','F03','F04','F08','F09','F07','F10',],axis=1)
y = df_3['T04']# loading the linear regression model

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20, random_state=20)

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
scaler = MinMaxScaler()
# fit the scaler to the train set, it will learn the parameters
scaler.fit(X_train)
# transform train and test sets
X_train_scaled_MM = scaler.transform(X_train)
X_test_scaled_MM = scaler.transform(X_test)
X_train_scaled_MM = pd.DataFrame(X_train_scaled_MM, columns=X_train.columns)
X_test_scaled_MM = pd.DataFrame(X_test_scaled_MM, columns=X_test.columns)

# Ensure y_train indices match X_train_scaled_MM
y_train = y_train.reset_index(drop=True)
X_train_scaled_MM = X_train_scaled_MM.reset_index(drop=True)
print(X_train_scaled_MM.index.equals(y_train.index))  # Should print True

import statsmodels.api as sm
X_sm = sm.add_constant(X_train_scaled_MM)
model = sm.OLS(y_train,X_sm).fit()
model.summary()

True


c:\users\nettemchandra sekhar\appdata\local\programs\python\python39\lib\site-packages\scipy\stats\_stats_py.py:1769: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=16
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    T04   R-squared:                       0.767
Model:                            OLS   Adj. R-squared:                  0.732
Method:                 Least Squares   F-statistic:                     21.45
Date:                Thu, 05 Sep 2024   Prob (F-statistic):           7.62e-05
Time:                        10:07:12   Log-Likelihood:                -70.765
No. Observations:                  16   AIC:                             147.5
Df Residuals:                      13   BIC:                             149.8
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        155.6559     10.976     14.182      0.000     131.944     179.367
F05          -79.2934     31.979     -2.480      0.028    -148.379     -10.207
F06          -40.8202     30.578     -1.335      0.205    -106.881      25.241
==============================================================================
Omnibus:                        1.151   Durbin-Watson:                   2.151
Prob(Omnibus):                  0.562   Jarque-Bera (JB):                0.886
Skew:                          -0.527   Prob(JB):                        0.642
Kurtosis:                       2.532   Cond. No.                         9.55
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [9]:
# can tune other metrics, such as MSE
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
scaler = MinMaxScaler()
# fit the scaler to the train set, it will learn the parameters
scaler.fit(X)
# transform train and test sets
X_scaled_MM = scaler.transform(X)
X_scaled_MM = pd.DataFrame(X_scaled_MM, columns=X.columns)

scores = cross_val_score(lin_reg_model, X_scaled_MM, y, cv=2)
print(scores)
print(np.mean(scores))

scores = cross_val_score(lin_reg_model, X_scaled_MM, y, cv=3)
print(scores)
print(np.mean(scores))

scores = cross_val_score(lin_reg_model, X_scaled_MM, y, cv=4)
print(scores)
print(np.mean(scores))

scores = cross_val_score(lin_reg_model, X_scaled_MM, y, cv=5)
print(scores)
print(np.mean(scores))


[0.53307525 0.8625477 ]
0.6978114787190265
[0.71126152 0.76104484 0.83235932]
0.7682218910555845
[0.46162422 0.69890455 0.85080881 0.90331436]
0.7286629860384899
[0.09103171 0.8962691  0.11897102 0.85674309 0.85788936]
0.5641808570585777


In [19]:

# Initialize the Leave-One-Out cross-validator
loo = LeaveOneOut()

# Drop the specified columns and set target variable
X = df_3.drop(['T04','F01','F02','F03','F04','F08','F09','F07','F10',],axis=1)
y = df_3['T04']# loading the linear regression model
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
# Apply MinMax Scaling
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)  # Scale the features and store them in X_scaled


# Initialize lists to store predictions and actual values
y_pred_loo = []
y_true_loo = []

# Loop over each training/test split
for train_index, test_index in loo.split(X_scaled):
    X_train_loo, X_test_loo = X_scaled[train_index], X_scaled[test_index]
    y_train_loo, y_test_loo = y.iloc[train_index], y.iloc[test_index]
    
    # Train the Lasso model
    linear_reg_model = LinearRegression()
    linear_reg_model.fit(X_train_loo, y_train_loo)
    
    # Predict the left-out sample
    y_pred_loo.append(linear_reg_model.predict(X_test_loo)[0])
    y_true_loo.append(y_test_loo.values[0])

# Convert lists to arrays
y_pred_loo = np.array(y_pred_loo)
y_true_loo = np.array(y_true_loo)

# Calculate LOO performance metrics
Q2_loo = r2_score(y_true_loo, y_pred_loo)
MAE_loo = mean_absolute_error(y_true_loo, y_pred_loo)
MSE_loo = mean_squared_error(y_true_loo, y_pred_loo)
RMSE_loo = np.sqrt(MSE_loo)

# Print the results
print("LOO Q^2 score: ", Q2_loo)
print("LOO Mean Absolute Error: ", MAE_loo)
print("LOO Mean Squared Error: ", MSE_loo)
print("LOO Root Mean Squared Error: ", RMSE_loo)



LOO Q^2 score:  0.7097866459749749
LOO Mean Absolute Error:  15.74702858436523
LOO Mean Squared Error:  435.5745147079985
LOO Root Mean Squared Error:  20.87042200598729


In [11]:
X_scaled_MM

F05       F06
0   0.673968  0.770115
1   0.831508  0.597701
2   1.000000  0.804598
3   0.503454  0.965517
4   0.336310  0.624138
5   0.170682  0.298851
6   0.000000  0.000000
7   0.667397  0.678161
8   0.832013  0.494253
9   0.669419  0.632184
10  0.503623  0.850575
11  0.336142  0.528736
12  0.170345  0.149425
13  0.000000  0.000000
14  0.667228  0.735632
15  0.830666  1.000000
16  0.999832  0.747126
17  0.505644  0.758621
18  0.340185  0.459770
19  0.171693  0.206897
20  0.000000  0.103448