In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.model_selection import GridSearchCV
from sklearn import metrics
import scipy.stats as stat
import pylab 
import math
from sklearn.neighbors import KNeighborsClassifier as knn
from sklearn.linear_model import LogisticRegression as LGR,Lasso
from sklearn.ensemble import RandomForestClassifier as rfc
from sklearn.feature_selection import SelectFromModel
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import StratifiedKFold

In [17]:
Fe_CAAC_dataset = df = pd.read_excel("F:\\Nitrogen_activation\\rajaraman\\office\\ofifice\\jupyter\\Extension\\T07\\heatmap\\agostic\\LR_F09\\N2_activation_extension_T07_heatmap_agostaic_descrptors.xlsx")

In [18]:
df_1=df.drop(['F00','T01','T02','T03',],axis=1)
df_2=df_1.drop([0,18,9])
df_3=df_1.drop([0,18,9,8,26,17])
df_4=df_1.drop([8,26,17])

In [19]:
#X = df.drop(['F01','F04','F05','F06','F07','F08','F09','F10','F11','F12','F13','F14','F15','T01','T02','T03','T04','T05'],axis=1)
#X = df_3.drop(['F01','F02','F19','F08','F03','F14','F07','F15','F17','F18','F09','F16','F11','F05','F04','T01','T07','T03','T04','T05','F03','T06','T08','T02',],axis=1)

#'F13','F10','F12','F09','F16','F11','F05','F04'

X = df_3.drop(['T04','F01','F02','F04','F06','F08','F04','F05','F03','F07','F10',],axis=1)
y = df_3['T04']# loading the linear regression model


X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20, random_state=20)

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
scaler = MinMaxScaler()
# fit the scaler to the train set, it will learn the parameters
scaler.fit(X_train)
# transform train and test sets
X_train_scaled_MM = scaler.transform(X_train)
X_test_scaled_MM = scaler.transform(X_test)
X_train_scaled_MM = pd.DataFrame(X_train_scaled_MM, columns=X_train.columns)
X_test_scaled_MM = pd.DataFrame(X_test_scaled_MM, columns=X_test.columns)

#LinearRegression_scaling
lin_reg_model = LinearRegression()
lin_reg_model.fit(X_train_scaled_MM,y_train)
# prediction on Training data
training_data_prediction_X_train_lin_reg = lin_reg_model.predict(X_train_scaled_MM)
# prediction on Test data
test_data_prediction_X_test_lin_reg = lin_reg_model.predict(X_test_scaled_MM)

# R squared Error
error_score_r2 = metrics.r2_score(y_train, training_data_prediction_X_train_lin_reg)
error_score_MAE = metrics.mean_absolute_error(y_train, training_data_prediction_X_train_lin_reg)
print("R squared Error : ", error_score_r2)
print("mean_absolute_error : ", error_score_MAE)
# R squared Error
error_score_r2 = metrics.r2_score(y_test, test_data_prediction_X_test_lin_reg)
error_score_MAE = metrics.mean_absolute_error(y_test, test_data_prediction_X_test_lin_reg)
print("R squared Error : ", error_score_r2)
print("mean_absolute_error : ", error_score_MAE)
scores = cross_val_score(lin_reg_model, X_train, y_train, cv=2)
print(scores)
print(np.mean(scores))
# can tune other metrics, such as MSE
scores = cross_val_score(lin_reg_model, X, y, cv=4)
print(scores)
print(np.mean(scores))
intercept = lin_reg_model.intercept_
print(intercept)
coeff = lin_reg_model.coef_
features = X.columns
df_coeff = pd.DataFrame({"features":features,"coeff":coeff})
df_coeff.sort_values("coeff")

R squared Error :  0.4376288679755075
mean_absolute_error :  25.532647714589878
R squared Error :  0.5647057911035598
mean_absolute_error :  16.741967141809972
[0.00718561 0.23295378]
0.12006969605147033
[ 0.25023737 -1.45714145  0.30327786  0.42203974]
-0.12039661992927875
142.13174090354804


features      coeff
0      F09 -88.966265

In [10]:
X = df_3.drop(['T04','F01','F02','F04','F06','F08','F04','F05','F03','F07','F10',],axis=1)
y = df_3['T04']# loading the linear regression model

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20, random_state=20)

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
scaler = MinMaxScaler()
# fit the scaler to the train set, it will learn the parameters
scaler.fit(X_train)
# transform train and test sets
X_train_scaled_MM = scaler.transform(X_train)
X_test_scaled_MM = scaler.transform(X_test)
X_train_scaled_MM = pd.DataFrame(X_train_scaled_MM, columns=X_train.columns)
X_test_scaled_MM = pd.DataFrame(X_test_scaled_MM, columns=X_test.columns)

# Ensure y_train indices match X_train_scaled_MM
y_train = y_train.reset_index(drop=True)
X_train_scaled_MM = X_train_scaled_MM.reset_index(drop=True)
print(X_train_scaled_MM.index.equals(y_train.index))  # Should print True

import statsmodels.api as sm
X_sm = sm.add_constant(X_train_scaled_MM)
model = sm.OLS(y_train,X_sm).fit()
model.summary()

True


c:\users\nettemchandra sekhar\appdata\local\programs\python\python39\lib\site-packages\scipy\stats\_stats_py.py:1769: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=16
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    T04   R-squared:                       0.438
Model:                            OLS   Adj. R-squared:                  0.397
Method:                 Least Squares   F-statistic:                     10.89
Date:                Thu, 05 Sep 2024   Prob (F-statistic):            0.00526
Time:                        09:25:41   Log-Likelihood:                -77.831
No. Observations:                  16   AIC:                             159.7
Df Residuals:                      14   BIC:                             161.2
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        142.1317     16.307      8.716      0.000     107.157     177.106
F09          -88.9663     26.954     -3.301      0.005    -146.776     -31.156
==============================================================================
Omnibus:                        0.543   Durbin-Watson:                   1.686
Prob(Omnibus):                  0.762   Jarque-Bera (JB):                0.590
Skew:                          -0.176   Prob(JB):                        0.745
Kurtosis:                       2.128   Cond. No.                         4.15
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [20]:
X = df_3.drop(['T04','F01','F02','F04','F06','F08','F04','F05','F03','F07','F10',],axis=1)
y = df_3['T04']# loading the linear regression model


import statsmodels.api as sm
X_sm = sm.add_constant(X)
model = sm.OLS(y,X_sm).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    T04   R-squared:                       0.458
Model:                            OLS   Adj. R-squared:                  0.429
Method:                 Least Squares   F-statistic:                     16.03
Date:                Thu, 05 Sep 2024   Prob (F-statistic):           0.000760
Time:                        10:02:28   Log-Likelihood:                -100.17
No. Observations:                  21   AIC:                             204.3
Df Residuals:                      19   BIC:                             206.4
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1176.2142    269.907      4.358      0.000     611.292    1741.137
F09         -353.3433     88.252     -4.004      0.001    -538.056    -168.630
==============================================================================
Omnibus:                        0.146   Durbin-Watson:                   1.133
Prob(Omnibus):                  0.930   Jarque-Bera (JB):                0.361
Skew:                           0.071   Prob(JB):                        0.835
Kurtosis:                       2.373   Cond. No.                         140.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [21]:
X = df_3.drop(['T04',],axis=1)
#X = df_5.drop(['T07','F14','F17','F18',],axis=1)
y = df_3['T04']# loading the linear regression model


import statsmodels.api as sm
X_sm = sm.add_constant(X)
model = sm.OLS(y,X_sm).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    T04   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.900
Method:                 Least Squares   F-statistic:                     18.99
Date:                Thu, 05 Sep 2024   Prob (F-statistic):           3.33e-05
Time:                        10:02:31   Log-Likelihood:                -75.140
No. Observations:                  21   AIC:                             172.3
Df Residuals:                      10   BIC:                             183.8
Df Model:                          10                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       -436.6290    988.439     -0.442      0.668   -2639.009    1765.751
F01           -1.6242      1.031     -1.576      0.146      -3.921       0.672
F02          -20.1282     25.492     -0.790      0.448     -76.927      36.671
F03           10.6529    373.419      0.029      0.978    -821.377     842.683
F04            1.4020      2.569      0.546      0.597      -4.322       7.126
F05            3.8501      5.429      0.709      0.494      -8.246      15.946
F06           80.4688    342.222      0.235      0.819    -682.049     842.986
F07           29.7462     20.789      1.431      0.183     -16.574      76.066
F08          139.4953     99.035      1.409      0.189     -81.169     360.159
F09          187.4257     99.234      1.889      0.088     -33.681     408.533
F10            0.0122      0.036      0.343      0.738      -0.067       0.092
==============================================================================
Omnibus:                        0.733   Durbin-Watson:                   2.062
Prob(Omnibus):                  0.693   Jarque-Bera (JB):                0.760
Skew:                          -0.352   Prob(JB):                        0.684
Kurtosis:                       2.390   Cond. No.                     7.47e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 7.47e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [23]:

# Initialize the Leave-One-Out cross-validator
loo = LeaveOneOut()

X = df_3.drop(['T04','F01','F02','F04','F06','F08','F04','F05','F03','F07','F10',],axis=1)
y = df_3['T04']# loading the linear regression model

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
# Apply MinMax Scaling
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)  # Scale the features and store them in X_scaled


# Initialize lists to store predictions and actual values
y_pred_loo = []
y_true_loo = []

# Loop over each training/test split
for train_index, test_index in loo.split(X_scaled):
    X_train_loo, X_test_loo = X_scaled[train_index], X_scaled[test_index]
    y_train_loo, y_test_loo = y.iloc[train_index], y.iloc[test_index]
    
    # Train the Lasso model
    linear_reg_model = LinearRegression()
    linear_reg_model.fit(X_train_loo, y_train_loo)
    
    # Predict the left-out sample
    y_pred_loo.append(linear_reg_model.predict(X_test_loo)[0])
    y_true_loo.append(y_test_loo.values[0])

# Convert lists to arrays
y_pred_loo = np.array(y_pred_loo)
y_true_loo = np.array(y_true_loo)

# Calculate LOO performance metrics
Q2_loo = r2_score(y_true_loo, y_pred_loo)
MAE_loo = mean_absolute_error(y_true_loo, y_pred_loo)
MSE_loo = mean_squared_error(y_true_loo, y_pred_loo)
RMSE_loo = np.sqrt(MSE_loo)

# Print the results
print("LOO Q^2 score: ", Q2_loo)
print("LOO Mean Absolute Error: ", MAE_loo)
print("LOO Mean Squared Error: ", MSE_loo)
print("LOO Root Mean Squared Error: ", RMSE_loo)



LOO Q^2 score:  0.33976578709700056
LOO Mean Absolute Error:  26.037764680493627
LOO Mean Squared Error:  990.930268681031
LOO Root Mean Squared Error:  31.47904491373636


In [24]:
# can tune other metrics, such as MSE
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
scaler = MinMaxScaler()
# fit the scaler to the train set, it will learn the parameters
scaler.fit(X)
# transform train and test sets
X_scaled_MM = scaler.transform(X)
X_scaled_MM = pd.DataFrame(X_scaled_MM, columns=X.columns)

scores = cross_val_score(lin_reg_model, X_scaled_MM, y, cv=2)
print(scores)
print(np.mean(scores))

scores = cross_val_score(lin_reg_model, X_scaled_MM, y, cv=3)
print(scores)
print(np.mean(scores))

scores = cross_val_score(lin_reg_model, X_scaled_MM, y, cv=4)
print(scores)
print(np.mean(scores))

scores = cross_val_score(lin_reg_model, X_scaled_MM, y, cv=5)
print(scores)
print(np.mean(scores))



[-0.04899261  0.38115561]
0.16608150381525927
[ 0.56413552 -1.9521058   0.15892465]
-0.409681877485142
[ 0.25023737 -1.45714145  0.30327786  0.42203974]
-0.12039661992927683
[-0.28332092  0.79881958 -4.19549701  0.40149149  0.22341899]
-0.6110175715407483


In [25]:
comparison_df_train_lin = pd.DataFrame({'Actual Barrier (kJ/mol)': y_train, 'Predicted Barrier (kJ/mol)': training_data_prediction_X_train_lin_reg})

comparison_df_train_lin.to_excel('predicted_vs_actual_comparison_train_lin.xlsx', index=False)

comparison_df_test_lin = pd.DataFrame({'Actual Barrier (kJ/mol)': y_test, 'Predicted Barrier (kJ/mol)': test_data_prediction_X_test_lin_reg})

comparison_df_test_lin.to_excel('predicted_vs_actual_comparison_test_lin.xlsx', index=False)

print(comparison_df_train_lin)

print(comparison_df_test_lin)

    Actual Barrier (kJ/mol)  Predicted Barrier (kJ/mol)
15               134.989547                   99.094344
16               172.156151                  123.823390
22                60.127639                  116.619412
19                48.921745                   87.917429
25               153.204294                  142.131741
13               111.384753                   60.906181
6                126.165031                  123.112205
11                84.663254                   65.843090
7                158.160792                  141.882514
1                 25.243201                   73.271817
3                 63.400511                   83.943158
10                54.848496                   53.165476
14                96.725090                   94.878857
12                77.707753                   60.906181
20                70.614886                  102.396594
4                 97.057793                  105.478546
    Actual Barrier (kJ/mol)  Predicted Barrier (