In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.model_selection import GridSearchCV
from sklearn import metrics
import scipy.stats as stat
import pylab 
import math
from sklearn.neighbors import KNeighborsClassifier as knn
from sklearn.linear_model import LogisticRegression as LGR,Lasso
from sklearn.ensemble import RandomForestClassifier as rfc
from sklearn.feature_selection import SelectFromModel
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import StratifiedKFold

In [10]:
Fe_CAAC_dataset = df = pd.read_excel("F:\\Nitrogen_activation\\rajaraman\\office\\ofifice\\jupyter\\Extension\\T07\\heatmap\\agostic\\LR_F03_F01\\N2_activation_extension_T07_heatmap_agostaic_descrptors.xlsx")

In [11]:
df_1=df.drop(['F00','T01','T02','T03',],axis=1)
df_2=df_1.drop([0,18,9])
df_3=df_1.drop([0,18,9,8,26,17])
df_4=df_1.drop([8,26,17])

# F03+F01

In [12]:
#X = df.drop(['F01','F04','F05','F06','F07','F08','F09','F10','F11','F12','F13','F14','F15','T01','T02','T03','T04','T05'],axis=1)
#X = df_3.drop(['F01','F02','F19','F08','F03','F14','F07','F15','F17','F18','F09','F16','F11','F05','F04','T01','T07','T03','T04','T05','F03','T06','T08','T02',],axis=1)

#'F13','F10','F12','F09','F16','F11','F05','F04'

X = df_3.drop(['T04','F02','F04','F06','F04','F05','F08','F09','F07','F10',],axis=1)
y = df_3['T04']# loading the linear regression model

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20, random_state=20)

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
scaler = MinMaxScaler()
# fit the scaler to the train set, it will learn the parameters
scaler.fit(X_train)
# transform train and test sets
X_train_scaled_MM = scaler.transform(X_train)
X_test_scaled_MM = scaler.transform(X_test)
X_train_scaled_MM = pd.DataFrame(X_train_scaled_MM, columns=X_train.columns)
X_test_scaled_MM = pd.DataFrame(X_test_scaled_MM, columns=X_test.columns)

#LinearRegression_scaling
lin_reg_model = LinearRegression()
lin_reg_model.fit(X_train_scaled_MM,y_train)
# prediction on Training data
training_data_prediction_X_train_lin_reg = lin_reg_model.predict(X_train_scaled_MM)
# prediction on Test data
test_data_prediction_X_test_lin_reg = lin_reg_model.predict(X_test_scaled_MM)


# R squared Error
error_score_r2 = metrics.r2_score(y_train, training_data_prediction_X_train_lin_reg)
error_score_MAE = metrics.mean_absolute_error(y_train, training_data_prediction_X_train_lin_reg)
print("R squared Error : ", error_score_r2)
print("mean_absolute_error : ", error_score_MAE)
# R squared Error
error_score_r2 = metrics.r2_score(y_test, test_data_prediction_X_test_lin_reg)
error_score_MAE = metrics.mean_absolute_error(y_test, test_data_prediction_X_test_lin_reg)
print("R squared Error : ", error_score_r2)
print("mean_absolute_error : ", error_score_MAE)

coeff = lin_reg_model.coef_
features = X.columns
df_coeff = pd.DataFrame({"features":features,"coeff":coeff})
df_coeff.sort_values("coeff")

R squared Error :  0.8492483224139211
mean_absolute_error :  13.061603636526428
R squared Error :  0.7792730219432247
mean_absolute_error :  10.344546002812843


features       coeff
1      F03 -107.664158
0      F01  -19.331905

In [13]:
X = df_3.drop(['T04','F02','F04','F06','F04','F05','F08','F09','F07','F10',],axis=1)
y = df_3['T04']# loading the linear regression model

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20, random_state=20)

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
scaler = MinMaxScaler()
# fit the scaler to the train set, it will learn the parameters
scaler.fit(X_train)
# transform train and test sets
X_train_scaled_MM = scaler.transform(X_train)
X_test_scaled_MM = scaler.transform(X_test)
X_train_scaled_MM = pd.DataFrame(X_train_scaled_MM, columns=X_train.columns)
X_test_scaled_MM = pd.DataFrame(X_test_scaled_MM, columns=X_test.columns)

# Ensure y_train indices match X_train_scaled_MM
y_train = y_train.reset_index(drop=True)
X_train_scaled_MM = X_train_scaled_MM.reset_index(drop=True)
print(X_train_scaled_MM.index.equals(y_train.index))  # Should print True

import statsmodels.api as sm
X_sm = sm.add_constant(X_train_scaled_MM)
model = sm.OLS(y_train,X_sm).fit()
model.summary()

True


c:\users\nettemchandra sekhar\appdata\local\programs\python\python39\lib\site-packages\scipy\stats\_stats_py.py:1769: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=16
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    T04   R-squared:                       0.849
Model:                            OLS   Adj. R-squared:                  0.826
Method:                 Least Squares   F-statistic:                     36.62
Date:                Thu, 05 Sep 2024   Prob (F-statistic):           4.56e-06
Time:                        09:31:27   Log-Likelihood:                -67.299
No. Observations:                  16   AIC:                             140.6
Df Residuals:                      13   BIC:                             142.9
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        158.8268     13.995     11.349      0.000     128.592     189.062
F01          -19.3319     20.508     -0.943      0.363     -63.637      24.974
F03         -107.6642     13.273     -8.111      0.000    -136.339     -78.989
==============================================================================
Omnibus:                        4.990   Durbin-Watson:                   2.796
Prob(Omnibus):                  0.083   Jarque-Bera (JB):                2.745
Skew:                          -0.986   Prob(JB):                        0.254
Kurtosis:                       3.476   Cond. No.                         6.80
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [14]:
# can tune other metrics, such as MSE
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
scaler = MinMaxScaler()
# fit the scaler to the train set, it will learn the parameters
scaler.fit(X)
# transform train and test sets
X_scaled_MM = scaler.transform(X)
X_scaled_MM = pd.DataFrame(X_scaled_MM, columns=X.columns)

scores = cross_val_score(lin_reg_model, X_scaled_MM, y, cv=2)
print(scores)
print(np.mean(scores))

scores = cross_val_score(lin_reg_model, X_scaled_MM, y, cv=3)
print(scores)
print(np.mean(scores))

scores = cross_val_score(lin_reg_model, X_scaled_MM, y, cv=4)
print(scores)
print(np.mean(scores))

scores = cross_val_score(lin_reg_model, X_scaled_MM, y, cv=5)
print(scores)
print(np.mean(scores))


[0.81938323 0.81211135]
0.8157472909091016
[0.84884601 0.80561419 0.80502444]
0.8198282102866639
[0.72093549 0.83824915 0.87882337 0.73666552]
0.7936683821961676
[0.57232011 0.88720323 0.63732526 0.90591938 0.58907191]
0.7183679768122274


In [15]:

# Initialize the Leave-One-Out cross-validator
loo = LeaveOneOut()

# Drop the specified columns and set target variable
X = df_3.drop(['T04','F02','F04','F06','F04','F05','F08','F09','F07','F10',],axis=1)
y = df_3['T04']# loading the linear regression model

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
# Apply MinMax Scaling
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)  # Scale the features and store them in X_scaled


# Initialize lists to store predictions and actual values
y_pred_loo = []
y_true_loo = []

# Loop over each training/test split
for train_index, test_index in loo.split(X_scaled):
    X_train_loo, X_test_loo = X_scaled[train_index], X_scaled[test_index]
    y_train_loo, y_test_loo = y.iloc[train_index], y.iloc[test_index]
    
    # Train the Lasso model
    linear_reg_model = LinearRegression()
    linear_reg_model.fit(X_train_loo, y_train_loo)
    
    # Predict the left-out sample
    y_pred_loo.append(linear_reg_model.predict(X_test_loo)[0])
    y_true_loo.append(y_test_loo.values[0])

# Convert lists to arrays
y_pred_loo = np.array(y_pred_loo)
y_true_loo = np.array(y_true_loo)

# Calculate LOO performance metrics
Q2_loo = r2_score(y_true_loo, y_pred_loo)
MAE_loo = mean_absolute_error(y_true_loo, y_pred_loo)
MSE_loo = mean_squared_error(y_true_loo, y_pred_loo)
RMSE_loo = np.sqrt(MSE_loo)

# Print the results
print("LOO Q^2 score: ", Q2_loo)
print("LOO Mean Absolute Error: ", MAE_loo)
print("LOO Mean Squared Error: ", MSE_loo)
print("LOO Root Mean Squared Error: ", RMSE_loo)



LOO Q^2 score:  0.7970912640681088
LOO Mean Absolute Error:  14.133634826163174
LOO Mean Squared Error:  304.54103147826106
LOO Root Mean Squared Error:  17.45110401889408


In [9]:
X_scaled_MM

F01       F03
0   0.348752  1.000000
1   0.072452  0.833894
2   1.000000  0.844990
3   0.465411  0.406859
4   0.492018  0.302623
5   0.586574  0.114324
6   0.512485  0.017989
7   0.326238  0.998655
8   0.000000  0.820444
9   0.563242  0.770007
10  0.435530  0.396772
11  0.463365  0.295898
12  0.591486  0.097512
13  0.510438  0.000000
14  0.009415  0.997983
15  0.077364  0.857431
16  0.889071  0.869200
17  0.542775  0.430397
18  0.600082  0.386685
19  0.640606  0.124580
20  0.544822  0.040350