In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.model_selection import GridSearchCV
from sklearn import metrics
import scipy.stats as stat
import pylab 
import math
from sklearn.neighbors import KNeighborsClassifier as knn
from sklearn.linear_model import LogisticRegression as LGR,Lasso
from sklearn.ensemble import RandomForestClassifier as rfc
from sklearn.feature_selection import SelectFromModel
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import StratifiedKFold

In [3]:
Fe_CAAC_dataset = df = pd.read_excel("F:\\Nitrogen_activation\\rajaraman\\office\\ofifice\\jupyter\\Extension\\T07\\heatmap\\agostic\\LR_F08_F03\\N2_activation_extension_T07_heatmap_agostaic_descrptors.xlsx")

In [4]:
df_1=df.drop(['F00','T01','T02','T03',],axis=1)
df_2=df_1.drop([0,18,9])
df_3=df_1.drop([0,18,9,8,26,17])
df_4=df_1.drop([8,26,17])

In [6]:
#X = df.drop(['F01','F04','F05','F06','F07','F08','F09','F10','F11','F12','F13','F14','F15','T01','T02','T03','T04','T05'],axis=1)
#X = df_3.drop(['F01','F02','F19','F08','F03','F14','F07','F15','F17','F18','F09','F16','F11','F05','F04','T01','T07','T03','T04','T05','F03','T06','T08','T02',],axis=1)

#'F13','F10','F12','F09','F16','F11','F05','F04'

X = df_3.drop(['T04','F01','F02','F04','F06','F04','F05','F09','F07','F10',],axis=1)
y = df_3['T04']# loading the linear regression model


X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20, random_state=20)

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
scaler = MinMaxScaler()
# fit the scaler to the train set, it will learn the parameters
scaler.fit(X_train)
# transform train and test sets
X_train_scaled_MM = scaler.transform(X_train)
X_test_scaled_MM = scaler.transform(X_test)
X_train_scaled_MM = pd.DataFrame(X_train_scaled_MM, columns=X_train.columns)
X_test_scaled_MM = pd.DataFrame(X_test_scaled_MM, columns=X_test.columns)

#LinearRegression_scaling
lin_reg_model = LinearRegression()
lin_reg_model.fit(X_train_scaled_MM,y_train)
# prediction on Training data
training_data_prediction_X_train_lin_reg = lin_reg_model.predict(X_train_scaled_MM)
# prediction on Test data
test_data_prediction_X_test_lin_reg = lin_reg_model.predict(X_test_scaled_MM)

# R squared Error
error_score_r2 = metrics.r2_score(y_train, training_data_prediction_X_train_lin_reg)
error_score_MAE = metrics.mean_absolute_error(y_train, training_data_prediction_X_train_lin_reg)
error_score_MSE = metrics.mean_squared_error(y_train, training_data_prediction_X_train_lin_reg)
print("R squared Error : ", error_score_r2)
print("mean_absolute_error : ", error_score_MAE)
print("mean_squared_error : ", error_score_MSE)
print("RMSE",np.sqrt(mean_squared_error(y_train,training_data_prediction_X_train_lin_reg)))


# R squared Error
error_score_r2 = metrics.r2_score(y_test, test_data_prediction_X_test_lin_reg)
error_score_MAE = metrics.mean_absolute_error(y_test, test_data_prediction_X_test_lin_reg)
error_score_MSE = metrics.mean_squared_error(y_test, test_data_prediction_X_test_lin_reg)
print("R squared Error : ", error_score_r2)
print("mean_absolute_error : ", error_score_MAE)
print("mean_squared_error : ", error_score_MSE)
print("RMSE",np.sqrt(mean_squared_error(y_test, test_data_prediction_X_test_lin_reg)))

scores = cross_val_score(lin_reg_model, X_train, y_train, cv=2)
print(scores)
print(np.mean(scores))
# can tune other metrics, such as MSE
scores = cross_val_score(lin_reg_model, X, y, cv=4)
print(scores)
print(np.mean(scores))
intercept = lin_reg_model.intercept_
print(intercept)
coeff = lin_reg_model.coef_
features = X.columns
df_coeff = pd.DataFrame({"features":features,"coeff":coeff})
df_coeff.sort_values("coeff")

R squared Error :  0.9188910866881459
mean_absolute_error :  8.946681183316674
mean_squared_error :  141.8285530670475
RMSE 11.909179361612097
R squared Error :  0.805023423049888
mean_absolute_error :  10.407425632453407
mean_squared_error :  138.0440806105273
RMSE 11.74921617004842
[0.87793535 0.8919725 ]
0.8849539246709239
[0.81435468 0.81564318 0.97404508 0.84726781]
0.862827686811941
136.70555958397173


features       coeff
0      F03 -124.256982
1      F08   36.178509

In [6]:
X = df_3.drop(['T04','F01','F02','F04','F06','F04','F05','F09','F07','F10',],axis=1)
y = df_3['T04']# loading the linear regression model

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20, random_state=20)

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
scaler = MinMaxScaler()
# fit the scaler to the train set, it will learn the parameters
scaler.fit(X_train)
# transform train and test sets
X_train_scaled_MM = scaler.transform(X_train)
X_test_scaled_MM = scaler.transform(X_test)
X_train_scaled_MM = pd.DataFrame(X_train_scaled_MM, columns=X_train.columns)
X_test_scaled_MM = pd.DataFrame(X_test_scaled_MM, columns=X_test.columns)

# Ensure y_train indices match X_train_scaled_MM
y_train = y_train.reset_index(drop=True)
X_train_scaled_MM = X_train_scaled_MM.reset_index(drop=True)
print(X_train_scaled_MM.index.equals(y_train.index))  # Should print True

import statsmodels.api as sm
X_sm = sm.add_constant(X_train_scaled_MM)
model = sm.OLS(y_train,X_sm).fit()
model.summary()

True


c:\users\nettemchandra sekhar\appdata\local\programs\python\python39\lib\site-packages\scipy\stats\_stats_py.py:1769: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=16
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    T04   R-squared:                       0.919
Model:                            OLS   Adj. R-squared:                  0.906
Method:                 Least Squares   F-statistic:                     73.64
Date:                Thu, 05 Sep 2024   Prob (F-statistic):           8.11e-08
Time:                        09:22:30   Log-Likelihood:                -62.340
No. Observations:                  16   AIC:                             130.7
Df Residuals:                      13   BIC:                             133.0
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        136.7056      6.351     21.526      0.000     122.986     150.425
F03         -124.2570     10.737    -11.573      0.000    -147.452    -101.062
F08           36.1785     10.107      3.580      0.003      14.344      58.013
==============================================================================
Omnibus:                        1.120   Durbin-Watson:                   2.365
Prob(Omnibus):                  0.571   Jarque-Bera (JB):                0.259
Skew:                          -0.300   Prob(JB):                        0.878
Kurtosis:                       3.172   Cond. No.                         5.20
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [7]:
X = df_3.drop(['T04','F01','F02','F04','F06','F04','F05','F09','F07','F10',],axis=1)
y = df_3['T04']# loading the linear regression model


import statsmodels.api as sm
X_sm = sm.add_constant(X)
model = sm.OLS(y,X_sm).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    T04   R-squared:                       0.907
Model:                            OLS   Adj. R-squared:                  0.897
Method:                 Least Squares   F-statistic:                     88.19
Date:                Thu, 05 Sep 2024   Prob (F-statistic):           5.01e-10
Time:                        09:22:34   Log-Likelihood:                -81.608
No. Observations:                  21   AIC:                             169.2
Df Residuals:                      18   BIC:                             172.4
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        989.2173     78.334     12.628      0.000     824.643    1153.792
F03         -413.5766     33.583    -12.315      0.000    -484.133    -343.021
F08          167.2721     43.448      3.850      0.001      75.991     258.553
==============================================================================
Omnibus:                        1.071   Durbin-Watson:                   2.250
Prob(Omnibus):                  0.585   Jarque-Bera (JB):                0.481
Skew:                          -0.371   Prob(JB):                        0.786
Kurtosis:                       3.013   Cond. No.                         75.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [9]:
X = df_3.drop(['T04',],axis=1)
#X = df_5.drop(['T07','F14','F17','F18',],axis=1)
y = df_3['T04']# loading the linear regression model


import statsmodels.api as sm
X_sm = sm.add_constant(X)
model = sm.OLS(y,X_sm).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    T04   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.900
Method:                 Least Squares   F-statistic:                     18.99
Date:                Thu, 05 Sep 2024   Prob (F-statistic):           3.33e-05
Time:                        09:22:47   Log-Likelihood:                -75.140
No. Observations:                  21   AIC:                             172.3
Df Residuals:                      10   BIC:                             183.8
Df Model:                          10                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       -436.6290    988.439     -0.442      0.668   -2639.009    1765.751
F01           -1.6242      1.031     -1.576      0.146      -3.921       0.672
F02          -20.1282     25.492     -0.790      0.448     -76.927      36.671
F03           10.6529    373.419      0.029      0.978    -821.377     842.683
F04            1.4020      2.569      0.546      0.597      -4.322       7.126
F05            3.8501      5.429      0.709      0.494      -8.246      15.946
F06           80.4688    342.222      0.235      0.819    -682.049     842.986
F07           29.7462     20.789      1.431      0.183     -16.574      76.066
F08          139.4953     99.035      1.409      0.189     -81.169     360.159
F09          187.4257     99.234      1.889      0.088     -33.681     408.533
F10            0.0122      0.036      0.343      0.738      -0.067       0.092
==============================================================================
Omnibus:                        0.733   Durbin-Watson:                   2.062
Prob(Omnibus):                  0.693   Jarque-Bera (JB):                0.760
Skew:                          -0.352   Prob(JB):                        0.684
Kurtosis:                       2.390   Cond. No.                     7.47e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 7.47e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [10]:

# Initialize the Leave-One-Out cross-validator
loo = LeaveOneOut()

# Drop the specified columns and set target variable
X = df_3.drop(['T04','F01','F02','F04','F06','F04','F05','F09','F07','F10',],axis=1)
y = df_3['T04']# loading the linear regression model

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
# Apply MinMax Scaling
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)  # Scale the features and store them in X_scaled


# Initialize lists to store predictions and actual values
y_pred_loo = []
y_true_loo = []

# Loop over each training/test split
for train_index, test_index in loo.split(X_scaled):
    X_train_loo, X_test_loo = X_scaled[train_index], X_scaled[test_index]
    y_train_loo, y_test_loo = y.iloc[train_index], y.iloc[test_index]
    
    # Train the Lasso model
    linear_reg_model = LinearRegression()
    linear_reg_model.fit(X_train_loo, y_train_loo)
    
    # Predict the left-out sample
    y_pred_loo.append(linear_reg_model.predict(X_test_loo)[0])
    y_true_loo.append(y_test_loo.values[0])

# Convert lists to arrays
y_pred_loo = np.array(y_pred_loo)
y_true_loo = np.array(y_true_loo)

# Calculate LOO performance metrics
Q2_loo = r2_score(y_true_loo, y_pred_loo)
MAE_loo = mean_absolute_error(y_true_loo, y_pred_loo)
MSE_loo = mean_squared_error(y_true_loo, y_pred_loo)
RMSE_loo = np.sqrt(MSE_loo)

# Print the results
print("LOO Q^2 score: ", Q2_loo)
print("LOO Mean Absolute Error: ", MAE_loo)
print("LOO Mean Squared Error: ", MSE_loo)
print("LOO Root Mean Squared Error: ", RMSE_loo)



LOO Q^2 score:  0.8719258354038354
LOO Mean Absolute Error:  10.833015735110868
LOO Mean Squared Error:  192.223553178729
LOO Root Mean Squared Error:  13.864470894294127


In [11]:
# can tune other metrics, such as MSE
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
scaler = MinMaxScaler()
# fit the scaler to the train set, it will learn the parameters
scaler.fit(X)
# transform train and test sets
X_scaled_MM = scaler.transform(X)
X_scaled_MM = pd.DataFrame(X_scaled_MM, columns=X.columns)

scores = cross_val_score(lin_reg_model, X_scaled_MM, y, cv=2)
print(scores)
print(np.mean(scores))

scores = cross_val_score(lin_reg_model, X_scaled_MM, y, cv=3)
print(scores)
print(np.mean(scores))

scores = cross_val_score(lin_reg_model, X_scaled_MM, y, cv=4)
print(scores)
print(np.mean(scores))

scores = cross_val_score(lin_reg_model, X_scaled_MM, y, cv=5)
print(scores)
print(np.mean(scores))



[0.84836376 0.90563739]
0.8770005720362191
[0.89621181 0.87371456 0.88761945]
0.8858486065442136
[0.81435468 0.81564318 0.97404508 0.84726781]
0.8628276868119411
[0.70381266 0.9179591  0.62192575 0.97665648 0.77906846]
0.7998844887944185


In [12]:
comparison_df_train_lin = pd.DataFrame({'Actual Barrier (kJ/mol)': y_train, 'Predicted Barrier (kJ/mol)': training_data_prediction_X_train_lin_reg})

comparison_df_train_lin.to_excel('predicted_vs_actual_comparison_train_lin.xlsx', index=False)

comparison_df_test_lin = pd.DataFrame({'Actual Barrier (kJ/mol)': y_test, 'Predicted Barrier (kJ/mol)': test_data_prediction_X_test_lin_reg})

comparison_df_test_lin.to_excel('predicted_vs_actual_comparison_test_lin.xlsx', index=False)

print(comparison_df_train_lin)

print(comparison_df_test_lin)

    Actual Barrier (kJ/mol)  Predicted Barrier (kJ/mol)
0                134.989547                  134.031579
1                172.156151                  163.924388
2                 60.127639                   83.976867
3                 48.921745                   48.842006
4                153.204294                  158.427800
5                111.384753                   87.403865
6                126.165031                  132.604217
7                 84.663254                   69.632690
8                158.160792                  162.136189
9                 25.243201                   48.627087
10                63.400511                   66.940342
11                54.848496                   48.436539
12                96.725090                  101.887506
13                77.707753                   76.078691
14                70.614886                   63.284177
15                97.057793                   89.136993
    Actual Barrier (kJ/mol)  Predicted Barrier (