In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.model_selection import GridSearchCV
from sklearn import metrics
import scipy.stats as stat
import pylab 
import math
from sklearn.neighbors import KNeighborsClassifier as knn
from sklearn.linear_model import LogisticRegression as LGR,Lasso
from sklearn.ensemble import RandomForestClassifier as rfc
from sklearn.feature_selection import SelectFromModel
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import StratifiedKFold

In [29]:
Fe_CAAC_dataset = df = pd.read_excel("F:\\Nitrogen_activation\\rajaraman\\office\\ofifice\\jupyter\\Extension\\T07\\heatmap\\agostic\\LR_F08\\N2_activation_extension_T07_heatmap_agostaic_descrptors.xlsx")

In [30]:
df_1=df.drop(['F00','T01','T02','T03',],axis=1)
df_2=df_1.drop([0,18,9])
df_3=df_1.drop([0,18,9,8,26,17])
df_4=df_1.drop([8,26,17])

In [21]:
#X = df.drop(['F01','F04','F05','F06','F07','F08','F09','F10','F11','F12','F13','F14','F15','T01','T02','T03','T04','T05'],axis=1)
#X = df_3.drop(['F01','F02','F19','F08','F03','F14','F07','F15','F17','F18','F09','F16','F11','F05','F04','T01','T07','T03','T04','T05','F03','T06','T08','T02',],axis=1)

#'F13','F10','F12','F09','F16','F11','F05','F04'

X = df_3.drop(['T04','F01','F02','F03','F04','F06','F04','F05','F09','F07','F10',],axis=1)
y = df_3['T04']# loading the linear regression model

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20, random_state=20)

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
scaler = MinMaxScaler()
# fit the scaler to the train set, it will learn the parameters
scaler.fit(X_train)
# transform train and test sets
X_train_scaled_MM = scaler.transform(X_train)
X_test_scaled_MM = scaler.transform(X_test)
X_train_scaled_MM = pd.DataFrame(X_train_scaled_MM, columns=X_train.columns)
X_test_scaled_MM = pd.DataFrame(X_test_scaled_MM, columns=X_test.columns)

#LinearRegression_scaling
lin_reg_model = LinearRegression()
lin_reg_model.fit(X_train_scaled_MM,y_train)
# prediction on Training data
training_data_prediction_X_train_lin_reg = lin_reg_model.predict(X_train_scaled_MM)
# prediction on Test data
test_data_prediction_X_test_lin_reg = lin_reg_model.predict(X_test_scaled_MM)

# R squared Error
error_score_r2 = metrics.r2_score(y_train, training_data_prediction_X_train_lin_reg)
error_score_MAE = metrics.mean_absolute_error(y_train, training_data_prediction_X_train_lin_reg)
print("R squared Error : ", error_score_r2)
print("mean_absolute_error : ", error_score_MAE)
# R squared Error
error_score_r2 = metrics.r2_score(y_test, test_data_prediction_X_test_lin_reg)
error_score_MAE = metrics.mean_absolute_error(y_test, test_data_prediction_X_test_lin_reg)
print("R squared Error : ", error_score_r2)
print("mean_absolute_error : ", error_score_MAE)
scores = cross_val_score(lin_reg_model, X_train, y_train, cv=2)
print(scores)
print(np.mean(scores))
# can tune other metrics, such as MSE
scores = cross_val_score(lin_reg_model, X, y, cv=4)
print(scores)
print(np.mean(scores))
intercept = lin_reg_model.intercept_
print(intercept)
coeff = lin_reg_model.coef_
features = X.columns
df_coeff = pd.DataFrame({"features":features,"coeff":coeff})
df_coeff.sort_values("coeff")

R squared Error :  0.08322231883063402
mean_absolute_error :  32.14089346936653
R squared Error :  0.4529491577196345
mean_absolute_error :  16.0154551108167
[-0.42008472 -0.67822013]
-0.549152424959099
[-0.06953296  0.08642592  0.03521634 -0.15392286]
-0.02545339202586988
114.48813327218934


features      coeff
0      F08 -30.358231

In [22]:
X = df_3.drop(['T04','F01','F02','F03','F04','F06','F04','F05','F09','F07','F10',],axis=1)
y = df_3['T04']# loading the linear regression model


X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20, random_state=20)

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
scaler = MinMaxScaler()
# fit the scaler to the train set, it will learn the parameters
scaler.fit(X_train)
# transform train and test sets
X_train_scaled_MM = scaler.transform(X_train)
X_test_scaled_MM = scaler.transform(X_test)
X_train_scaled_MM = pd.DataFrame(X_train_scaled_MM, columns=X_train.columns)
X_test_scaled_MM = pd.DataFrame(X_test_scaled_MM, columns=X_test.columns)

# Ensure y_train indices match X_train_scaled_MM
y_train = y_train.reset_index(drop=True)
X_train_scaled_MM = X_train_scaled_MM.reset_index(drop=True)
print(X_train_scaled_MM.index.equals(y_train.index))  # Should print True

import statsmodels.api as sm
X_sm = sm.add_constant(X_train_scaled_MM)
model = sm.OLS(y_train,X_sm).fit()
model.summary()

True


c:\users\nettemchandra sekhar\appdata\local\programs\python\python39\lib\site-packages\scipy\stats\_stats_py.py:1769: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=16
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    T04   R-squared:                       0.083
Model:                            OLS   Adj. R-squared:                  0.018
Method:                 Least Squares   F-statistic:                     1.271
Date:                Thu, 05 Sep 2024   Prob (F-statistic):              0.279
Time:                        09:21:01   Log-Likelihood:                -81.741
No. Observations:                  16   AIC:                             167.5
Df Residuals:                      14   BIC:                             169.0
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        114.4881     19.611      5.838      0.000      72.426     156.550
F08          -30.3582     26.929     -1.127      0.279     -88.116      27.399
==============================================================================
Omnibus:                        1.542   Durbin-Watson:                   2.247
Prob(Omnibus):                  0.462   Jarque-Bera (JB):                1.220
Skew:                           0.613   Prob(JB):                        0.543
Kurtosis:                       2.429   Cond. No.                         3.57
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [23]:
X = df_3.drop(['T04','F01','F02','F03','F04','F06','F04','F05','F09','F07','F10',],axis=1)
y = df_3['T04']# loading the linear regression model



import statsmodels.api as sm
X_sm = sm.add_constant(X)
model = sm.OLS(y,X_sm).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    T04   R-squared:                       0.127
Model:                            OLS   Adj. R-squared:                  0.081
Method:                 Least Squares   F-statistic:                     2.769
Date:                Thu, 05 Sep 2024   Prob (F-statistic):              0.112
Time:                        09:21:03   Log-Likelihood:                -105.16
No. Observations:                  21   AIC:                             214.3
Df Residuals:                      19   BIC:                             216.4
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         36.4443     36.665      0.994      0.333     -40.297     113.185
F08         -168.2857    101.126     -1.664      0.112    -379.944      43.373
==============================================================================
Omnibus:                        2.980   Durbin-Watson:                   1.514
Prob(Omnibus):                  0.225   Jarque-Bera (JB):                1.991
Skew:                           0.754   Prob(JB):                        0.369
Kurtosis:                       2.964   Cond. No.                         13.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [24]:
X = df_3.drop(['T04',],axis=1)
#X = df_5.drop(['T07','F14','F17','F18',],axis=1)
y = df_3['T04']# loading the linear regression model


import statsmodels.api as sm
X_sm = sm.add_constant(X)
model = sm.OLS(y,X_sm).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    T04   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.900
Method:                 Least Squares   F-statistic:                     18.99
Date:                Thu, 05 Sep 2024   Prob (F-statistic):           3.33e-05
Time:                        09:21:03   Log-Likelihood:                -75.140
No. Observations:                  21   AIC:                             172.3
Df Residuals:                      10   BIC:                             183.8
Df Model:                          10                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       -436.6290    988.439     -0.442      0.668   -2639.009    1765.751
F01           -1.6242      1.031     -1.576      0.146      -3.921       0.672
F02          -20.1282     25.492     -0.790      0.448     -76.927      36.671
F03           10.6529    373.419      0.029      0.978    -821.377     842.683
F04            1.4020      2.569      0.546      0.597      -4.322       7.126
F05            3.8501      5.429      0.709      0.494      -8.246      15.946
F06           80.4688    342.222      0.235      0.819    -682.049     842.986
F07           29.7462     20.789      1.431      0.183     -16.574      76.066
F08          139.4953     99.035      1.409      0.189     -81.169     360.159
F09          187.4257     99.234      1.889      0.088     -33.681     408.533
F10            0.0122      0.036      0.343      0.738      -0.067       0.092
==============================================================================
Omnibus:                        0.733   Durbin-Watson:                   2.062
Prob(Omnibus):                  0.693   Jarque-Bera (JB):                0.760
Skew:                          -0.352   Prob(JB):                        0.684
Kurtosis:                       2.390   Cond. No.                     7.47e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 7.47e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [25]:

# Initialize the Leave-One-Out cross-validator
loo = LeaveOneOut()

# Drop the specified columns and set target variable
X = df_3.drop(['T04','F01','F02','F03','F04','F06','F04','F05','F09','F07','F10',],axis=1)
y = df_3['T04']# loading the linear regression model


from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
# Apply MinMax Scaling
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)  # Scale the features and store them in X_scaled


# Initialize lists to store predictions and actual values
y_pred_loo = []
y_true_loo = []

# Loop over each training/test split
for train_index, test_index in loo.split(X_scaled):
    X_train_loo, X_test_loo = X_scaled[train_index], X_scaled[test_index]
    y_train_loo, y_test_loo = y.iloc[train_index], y.iloc[test_index]
    
    # Train the Lasso model
    linear_reg_model = LinearRegression()
    linear_reg_model.fit(X_train_loo, y_train_loo)
    
    # Predict the left-out sample
    y_pred_loo.append(linear_reg_model.predict(X_test_loo)[0])
    y_true_loo.append(y_test_loo.values[0])

# Convert lists to arrays
y_pred_loo = np.array(y_pred_loo)
y_true_loo = np.array(y_true_loo)

# Calculate LOO performance metrics
Q2_loo = r2_score(y_true_loo, y_pred_loo)
MAE_loo = mean_absolute_error(y_true_loo, y_pred_loo)
MSE_loo = mean_squared_error(y_true_loo, y_pred_loo)
RMSE_loo = np.sqrt(MSE_loo)

# Print the results
print("LOO Q^2 score: ", Q2_loo)
print("LOO Mean Absolute Error: ", MAE_loo)
print("LOO Mean Squared Error: ", MSE_loo)
print("LOO Root Mean Squared Error: ", RMSE_loo)



LOO Q^2 score:  -0.030512146989434497
LOO Mean Absolute Error:  30.47984185925724
LOO Mean Squared Error:  1546.6718608920896
LOO Root Mean Squared Error:  39.32774924772698


In [26]:
# can tune other metrics, such as MSE
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
scaler = MinMaxScaler()
# fit the scaler to the train set, it will learn the parameters
scaler.fit(X)
# transform train and test sets
X_scaled_MM = scaler.transform(X)
X_scaled_MM = pd.DataFrame(X_scaled_MM, columns=X.columns)

scores = cross_val_score(lin_reg_model, X_scaled_MM, y, cv=2)
print(scores)
print(np.mean(scores))

scores = cross_val_score(lin_reg_model, X_scaled_MM, y, cv=3)
print(scores)
print(np.mean(scores))

scores = cross_val_score(lin_reg_model, X_scaled_MM, y, cv=4)
print(scores)
print(np.mean(scores))

scores = cross_val_score(lin_reg_model, X_scaled_MM, y, cv=5)
print(scores)
print(np.mean(scores))



[ 0.03921471 -0.06503472]
-0.012910002110460617
[ 0.14071657 -0.01375953  0.06504676]
0.06400126889107412
[-0.06953296  0.08642592  0.03521634 -0.15392286]
-0.025453392025869742
[-0.80289966 -0.03410897  0.35334202  0.10747428 -0.74755471]
-0.22474940658337972


In [27]:
comparison_df_train_lin = pd.DataFrame({'Actual Barrier (kJ/mol)': y_train, 'Predicted Barrier (kJ/mol)': training_data_prediction_X_train_lin_reg})

comparison_df_train_lin.to_excel('predicted_vs_actual_comparison_train_lin.xlsx', index=False)

comparison_df_test_lin = pd.DataFrame({'Actual Barrier (kJ/mol)': y_test, 'Predicted Barrier (kJ/mol)': test_data_prediction_X_test_lin_reg})

comparison_df_test_lin.to_excel('predicted_vs_actual_comparison_test_lin.xlsx', index=False)

print(comparison_df_train_lin)

print(comparison_df_test_lin)

    Actual Barrier (kJ/mol)  Predicted Barrier (kJ/mol)
0                134.989547                  106.564680
1                172.156151                   91.648179
2                 60.127639                  113.857859
3                 48.921745                   84.159915
4                153.204294                   92.053356
5                111.384753                  114.488133
6                126.165031                  106.009438
7                 84.663254                   85.225380
8                158.160792                   91.273016
9                 25.243201                   84.129902
10                63.400511                   84.925249
11                54.848496                   84.430033
12                96.725090                  112.852420
13                77.707753                   85.075314
14                70.614886                   86.696021
15                97.057793                  111.982041
    Actual Barrier (kJ/mol)  Predicted Barrier (