In [5]:
from sklearn.model_selection import GridSearchCV
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.model_selection import GridSearchCV

from sklearn import metrics
import scipy.stats as stat
import pylab 
import math
from sklearn.neighbors import KNeighborsClassifier as knn
from sklearn.linear_model import LogisticRegression as LGR,Lasso
from sklearn.ensemble import RandomForestClassifier as rfc
from sklearn.feature_selection import SelectFromModel
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import StratifiedKFold

In [19]:
Fe_CAAC_dataset = df = pd.read_excel("F:\\Nitrogen_activation\\rajaraman\\office\\ofifice\\jupyter\\Extension\\T07\\heatmap\\agostic\\elasticnet\\N2_activation_extension_T07_heatmap_agostaic_descrptors.xlsx")

In [7]:
df_1=df.drop(['F00','T01','T02','T03',],axis=1)
df_2=df_1.drop([0,18,9])
df_3=df_1.drop([0,18,9,8,26,17])
df_4=df_1.drop([8,26,17])

In [11]:
X = df_3.drop(['T04','F01','F02','F04','F06','F04','F05','F09','F07','F10',],axis=1)
y = df_3['T04']# loading the linear regression model


X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20, random_state=20)
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
scaler = MinMaxScaler()
# fit the scaler to the train set, it will learn the parameters
scaler.fit(X_train)
# transform train and test sets
X_train_scaled_MM = scaler.transform(X_train)
X_test_scaled_MM = scaler.transform(X_test)
X_train_scaled_MM = pd.DataFrame(X_train_scaled_MM, columns=X_train.columns)
X_test_scaled_MM = pd.DataFrame(X_test_scaled_MM, columns=X_test.columns)


ElasticNet_reg_model = ElasticNet()

# Define the parameter grid
param_grid = {
    'alpha': [0.01, 0.1, 1, 10, 100],  # Regularization strength
    'l1_ratio': [0.1, 0.3, 0.5, 0.7, 0.9, 1]  # Balance between L1 and L2
}

# Set up Grid Search
grid_search = GridSearchCV(
    estimator=ElasticNet_reg_model,
    param_grid=param_grid,
    cv=5,
    scoring='neg_mean_squared_error',
    n_jobs=-1,
    verbose=2
)


# Fit the model
grid_search.fit(X_train_scaled_MM, y_train)


#print("Best parameters found: ", grid_search.best_params_)
print("Best score: ", grid_search.best_score_)
best_params = grid_search.best_params_
print("Best parameters found: ", best_params)





Fitting 5 folds for each of 30 candidates, totalling 150 fits
Best score:  -212.04933071470492
Best parameters found:  {'alpha': 0.01, 'l1_ratio': 0.7}


In [18]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

X = df_3.drop(['T04','F01','F02','F04','F06','F04','F05','F09','F07','F10',],axis=1)
y = df_3['T04']# loading the linear regression model

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20, random_state=20)

scaler = MinMaxScaler()
# fit the scaler to the train set, it will learn the parameters
scaler.fit(X_train)
# transform train and test sets
X_train_scaled_MM = scaler.transform(X_train)
X_test_scaled_MM = scaler.transform(X_test)
X_train_scaled_MM = pd.DataFrame(X_train_scaled_MM, columns=X_train.columns)
X_test_scaled_MM = pd.DataFrame(X_test_scaled_MM, columns=X_test.columns)


#LassoRegression_scaling_MM
ElasticNet_reg_model = ElasticNet(alpha=best_params['alpha'],l1_ratio=best_params['l1_ratio'])

ElasticNet_reg_model.fit(X_train_scaled_MM,y_train)
# prediction on Training data
training_data_prediction_X_train_ElasticNet_reg = ElasticNet_reg_model.predict(X_train_scaled_MM)
# prediction on Test data
test_data_prediction_X_test_ElasticNet_reg = ElasticNet_reg_model.predict(X_test_scaled_MM)

# R squared Error
error_score_r2 = metrics.r2_score(y_train, training_data_prediction_X_train_ElasticNet_reg)
error_score_MAE = metrics.mean_absolute_error(y_train, training_data_prediction_X_train_ElasticNet_reg)
error_score_MSE = metrics.mean_squared_error(y_train, training_data_prediction_X_train_ElasticNet_reg)
print("R squared Error : ", error_score_r2)
print("mean_absolute_error : ", error_score_MAE)
print("mean_squared_error : ", error_score_MSE)
print("RMSE",np.sqrt(mean_squared_error(y_train,training_data_prediction_X_train_ElasticNet_reg)))
# R squared Error
error_score_r2 = metrics.r2_score(y_test, test_data_prediction_X_test_ElasticNet_reg)
error_score_MAE = metrics.mean_absolute_error(y_test, test_data_prediction_X_test_ElasticNet_reg)
error_score_MSE = metrics.mean_squared_error(y_test, test_data_prediction_X_test_ElasticNet_reg)
print("R squared Error : ", error_score_r2)
print("mean_absolute_error : ", error_score_MAE)
print("mean_squared_error : ", error_score_MSE)
print("RMSE",np.sqrt(mean_squared_error(y_test,test_data_prediction_X_test_ElasticNet_reg)))
coeff = ElasticNet_reg_model.coef_
features = X_train_scaled_MM.columns
df_coeff = pd.DataFrame({"features":features,"coeff":coeff})
df_coeff.sort_values("coeff")


R squared Error :  0.9177666446634186
mean_absolute_error :  8.787235562876454
mean_squared_error :  143.79477328703328
RMSE 11.991445838056114
R squared Error :  0.812930803355357
mean_absolute_error :  10.478958625162452
mean_squared_error :  132.4456284201109
RMSE 11.50850244037472


features       coeff
0      F03 -119.782762
1      F08   33.109280

In [13]:
# can tune other metrics, such as MSE
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
scaler = MinMaxScaler()
# fit the scaler to the train set, it will learn the parameters
scaler.fit(X)
# transform train and test sets
X_scaled_MM = scaler.transform(X)
X_scaled_MM = pd.DataFrame(X_scaled_MM, columns=X.columns)

scores = cross_val_score(ElasticNet_reg_model, X_scaled_MM, y, cv=2)
print(scores)
print(np.mean(scores))

scores = cross_val_score(ElasticNet_reg_model, X_scaled_MM, y, cv=3)
print(scores)
print(np.mean(scores))

scores = cross_val_score(ElasticNet_reg_model, X_scaled_MM, y, cv=4)
print(scores)
print(np.mean(scores))

scores = cross_val_score(ElasticNet_reg_model, X_scaled_MM, y, cv=5)
print(scores)
print(np.mean(scores))

[0.85818174 0.89102688]
0.8746043112976696
[0.89469749 0.87376267 0.88310566]
0.883855271933847
[0.80511302 0.84161752 0.96394444 0.84032887]
0.8627509609037235
[0.68436255 0.93403916 0.66099821 0.96634697 0.76898286]
0.8029459493787667


In [16]:

# Initialize the Leave-One-Out cross-validator
loo = LeaveOneOut()

X = df_3.drop(['T04','F01','F02','F04','F06','F04','F05','F09','F07','F10',],axis=1)
y = df_3['T04']# loading the linear regression model

# Apply MinMax Scaling
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)  # Scale the features and store them in X_scaled


# Initialize lists to store predictions and actual values
y_pred_loo = []
y_true_loo = []

# Loop over each training/test split
for train_index, test_index in loo.split(X_scaled):
    X_train_loo, X_test_loo = X_scaled[train_index], X_scaled[test_index]
    y_train_loo, y_test_loo = y.iloc[train_index], y.iloc[test_index]
    
    # Train the Lasso model
    ElasticNet_reg_model = ElasticNet(alpha=best_params['alpha'],l1_ratio=best_params['l1_ratio'])
    ElasticNet_reg_model.fit(X_train_loo, y_train_loo)
    
    # Predict the left-out sample
    y_pred_loo.append(ElasticNet_reg_model.predict(X_test_loo)[0])
    y_true_loo.append(y_test_loo.values[0])

# Convert lists to arrays
y_pred_loo = np.array(y_pred_loo)
y_true_loo = np.array(y_true_loo)

# Calculate LOO performance metrics
Q2_loo = r2_score(y_true_loo, y_pred_loo)
MAE_loo = mean_absolute_error(y_true_loo, y_pred_loo)
MSE_loo = mean_squared_error(y_true_loo, y_pred_loo)
RMSE_loo = np.sqrt(MSE_loo)

# Print the results
print("LOO Q^2 score: ", Q2_loo)
print("LOO Mean Absolute Error: ", MAE_loo)
print("LOO Mean Squared Error: ", MSE_loo)
print("LOO Root Mean Squared Error: ", RMSE_loo)



LOO Q^2 score:  0.8703505223816561
LOO Mean Absolute Error:  10.606471047656974
LOO Mean Squared Error:  194.58790407999646
LOO Root Mean Squared Error:  13.949476838935446


In [17]:
comparison_df_train_ElasticNet = pd.DataFrame({'Actual Barrier (kJ/mol)': y_train, 'Predicted Barrier (kJ/mol)': training_data_prediction_X_train_ElasticNet_reg})

comparison_df_train_ElasticNet.to_excel('predicted_vs_actual_comparison_train_ElasticNet.xlsx', index=False)

comparison_df_test_ElasticNet = pd.DataFrame({'Actual Barrier (kJ/mol)': y_test, 'Predicted Barrier (kJ/mol)': test_data_prediction_X_test_ElasticNet_reg})

comparison_df_test_ElasticNet.to_excel('predicted_vs_actual_comparison_test_ElasticNet.xlsx', index=False)

print(comparison_df_train_ElasticNet)

print(comparison_df_test_ElasticNet)

    Actual Barrier (kJ/mol)  Predicted Barrier (kJ/mol)
15               134.989547                  133.277768
16               172.156151                  161.226224
22                60.127639                   85.449799
19                48.921745                   49.851969
25               153.204294                  155.951133
13               111.384753                   88.790075
6                126.165031                  131.869493
11                84.663254                   69.956025
7                158.160792                  159.480584
1                 25.243201                   49.643042
3                 63.400511                   67.343158
10                54.848496                   49.476820
14                96.725090                  102.657010
12                77.707753                   76.161187
20                70.614886                   63.921683
4                 97.057793                   90.314968
    Actual Barrier (kJ/mol)  Predicted Barrier (