In [35]:
from sklearn.model_selection import GridSearchCV
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
import shap
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.model_selection import GridSearchCV
from sklearn import metrics
import scipy.stats as stat
import pylab 
import math
from sklearn.neighbors import KNeighborsClassifier as knn
from sklearn.linear_model import LogisticRegression as LGR,Lasso
from sklearn.ensemble import RandomForestClassifier as rfc
from sklearn.feature_selection import SelectFromModel
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import StratifiedKFold
from sklearn.ensemble import RandomForestRegressor
import xgboost as xgb
import xgboost as xgb
from sklearn.ensemble import GradientBoostingRegressor

In [36]:
Fe_CAAC_dataset = df = pd.read_excel("F:\\Nitrogen_activation\\rajaraman\\office\\ofifice\\jupyter\\Extension\\T07\\heatmap\\agostic\\xgboost\\N2_activation_extension_T07_heatmap_agostaic_descrptors.xlsx")

In [37]:
df_1=df.drop(['F00','T01','T02','T03',],axis=1)
df_2=df_1.drop([0,18,9])
df_3=df_1.drop([0,18,9,8,26,17])
df_4=df_1.drop([8,26,17])

In [38]:
X = df_3.drop(['T04','F01','F02','F04','F06','F04','F05','F09','F07','F10',],axis=1)
y = df_3['T04']# loading the linear regression model


X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20, random_state=20)

#gb_reg_model = GradientBoostingRegressor(learning_rate=0.001,max_depth=2, max_features='sqrt', min_samples_leaf= 2, min_samples_split= 2, n_estimators= 200, subsample= 0.8)

gb_reg_model = GradientBoostingRegressor()
gbr_reg_model.fit(X_train_scaled_MM,y_train)

# prediction on Training data
training_data_prediction_X_train_gbr_reg = gbr_reg_model.predict(X_train_scaled_MM)
# prediction on Test data
test_data_prediction_X_test_gbr_reg = gbr_reg_model.predict(X_test_scaled_MM)
error_score_r2 = metrics.r2_score(y_train, training_data_prediction_X_train_gbr_reg)
error_score_MAE = metrics.mean_absolute_error(y_train, training_data_prediction_X_train_gbr_reg)
error_score_MSE = metrics.mean_squared_error(y_train, training_data_prediction_X_train_gbr_reg)
print("R squared Error : ", error_score_r2)
print("mean_absolute_error : ", error_score_MAE)
print("mean_squared_error : ", error_score_MSE)
print("RMSE",np.sqrt(mean_squared_error(y_train,training_data_prediction_X_train_gbr_reg)))
# R squared Error
error_score_r2 = metrics.r2_score(y_test, test_data_prediction_X_test_gbr_reg)
error_score_MAE = metrics.mean_absolute_error(y_test, test_data_prediction_X_test_gbr_reg)
error_score_MSE = metrics.mean_squared_error(y_test, test_data_prediction_X_test_gbr_reg)
print("R squared Error : ", error_score_r2)
print("mean_absolute_error : ", error_score_MAE)
print("mean_squared_error : ", error_score_MSE)
print("RMSE",np.sqrt(mean_squared_error(y_test,test_data_prediction_X_test_gbr_reg)))

R squared Error :  0.999999626717236
mean_absolute_error :  0.020996227149000513
mean_squared_error :  0.0006527291778554793
RMSE 0.025548565084080148
R squared Error :  0.8266646199661754
mean_absolute_error :  9.331480910042625
mean_squared_error :  122.7220394794808
RMSE 11.077997990588408


In [8]:

X = df_3.drop(['T04','F01','F02','F04','F06','F04','F05','F09','F07','F10',],axis=1)
y = df_3['T04']# loading the linear regression model


X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20, random_state=20)

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
scaler = MinMaxScaler()
# fit the scaler to the train set, it will learn the parameters
scaler.fit(X_train)
# transform train and test sets
X_train_scaled_MM = scaler.transform(X_train)
X_test_scaled_MM = scaler.transform(X_test)
X_train_scaled_MM = pd.DataFrame(X_train_scaled_MM, columns=X_train.columns)
X_test_scaled_MM = pd.DataFrame(X_test_scaled_MM, columns=X_test.columns)

param_grid = {
    'n_estimators': [100, 200],
    'learning_rate': [0.01, 0.1, 0.2],
    'max_depth': [3, 4, 5],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'subsample': [0.8, 0.9, 1.0],
    'max_features': [None, 'sqrt', 'log2']
}

gbr_reg_model= GradientBoostingRegressor()


# Set up Grid Search
grid_search = GridSearchCV(
    estimator=gbr_reg_model,
    param_grid=param_grid,
    cv=5,
    scoring='neg_mean_squared_error',
    n_jobs=-1,
    verbose=2
)


# Fit the model
grid_search.fit(X_train_scaled_MM, y_train)


#print("Best parameters found: ", grid_search.best_params_)
print("Best score: ", grid_search.best_score_)
best_params = grid_search.best_params_
print("Best parameters found: ", best_params)




Fitting 5 folds for each of 1458 candidates, totalling 7290 fits
Best score:  -229.45939277566427
Best parameters found:  {'learning_rate': 0.2, 'max_depth': 4, 'max_features': 'sqrt', 'min_samples_leaf': 4, 'min_samples_split': 2, 'n_estimators': 100, 'subsample': 0.8}


In [22]:
gb_reg_model = GradientBoostingRegressor(
    n_estimators=best_params['n_estimators'],
    learning_rate=best_params['learning_rate'],
    min_samples_split=best_params['min_samples_split'],
    min_samples_leaf=best_params['min_samples_leaf'],
    subsample=best_params['subsample'],
    max_features=best_params['max_features']
)

gbr_reg_model.fit(X_train_scaled_MM,y_train)

# prediction on Training data
training_data_prediction_X_train_gbr_reg = gbr_reg_model.predict(X_train_scaled_MM)
# prediction on Test data
test_data_prediction_X_test_gbr_reg = gbr_reg_model.predict(X_test_scaled_MM)
error_score_r2 = metrics.r2_score(y_train, training_data_prediction_X_train_gbr_reg)
error_score_MAE = metrics.mean_absolute_error(y_train, training_data_prediction_X_train_gbr_reg)
error_score_MSE = metrics.mean_squared_error(y_train, training_data_prediction_X_train_gbr_reg)
print("R squared Error : ", error_score_r2)
print("mean_absolute_error : ", error_score_MAE)
print("mean_squared_error : ", error_score_MSE)
print("RMSE",np.sqrt(mean_squared_error(y_train,training_data_prediction_X_train_gbr_reg)))
# R squared Error
error_score_r2 = metrics.r2_score(y_test, test_data_prediction_X_test_gbr_reg)
error_score_MAE = metrics.mean_absolute_error(y_test, test_data_prediction_X_test_gbr_reg)
error_score_MSE = metrics.mean_squared_error(y_test, test_data_prediction_X_test_gbr_reg)
print("R squared Error : ", error_score_r2)
print("mean_absolute_error : ", error_score_MAE)
print("mean_squared_error : ", error_score_MSE)
print("RMSE",np.sqrt(mean_squared_error(y_test,test_data_prediction_X_test_gbr_reg)))

R squared Error :  0.999999626717236
mean_absolute_error :  0.020996227149000513
mean_squared_error :  0.0006527291778554793
RMSE 0.025548565084080148
R squared Error :  0.823471923021769
mean_absolute_error :  9.549654210021501
mean_squared_error :  124.98247979109522
RMSE 11.17955633248007


In [34]:
X = df_3.drop(['T04','F01','F02','F04','F06','F04','F05','F09','F07','F10',],axis=1)
y = df_3['T04']# loading the linear regression model


X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20, random_state=20)

#gb_reg_model = GradientBoostingRegressor(learning_rate=0.001,max_depth=2, max_features='sqrt', min_samples_leaf= 2, min_samples_split= 2, n_estimators= 200, subsample= 0.8)

gb_reg_model = GradientBoostingRegressor(learning_rate=0.001,max_depth=2, max_features='sqrt', min_samples_leaf= 3, min_samples_split= 2, n_estimators= 200, subsample= 0.8)

gbr_reg_model.fit(X_train_scaled_MM,y_train)

# prediction on Training data
training_data_prediction_X_train_gbr_reg = gbr_reg_model.predict(X_train_scaled_MM)
# prediction on Test data
test_data_prediction_X_test_gbr_reg = gbr_reg_model.predict(X_test_scaled_MM)
error_score_r2 = metrics.r2_score(y_train, training_data_prediction_X_train_gbr_reg)
error_score_MAE = metrics.mean_absolute_error(y_train, training_data_prediction_X_train_gbr_reg)
error_score_MSE = metrics.mean_squared_error(y_train, training_data_prediction_X_train_gbr_reg)
print("R squared Error : ", error_score_r2)
print("mean_absolute_error : ", error_score_MAE)
print("mean_squared_error : ", error_score_MSE)
print("RMSE",np.sqrt(mean_squared_error(y_train,training_data_prediction_X_train_gbr_reg)))
# R squared Error
error_score_r2 = metrics.r2_score(y_test, test_data_prediction_X_test_gbr_reg)
error_score_MAE = metrics.mean_absolute_error(y_test, test_data_prediction_X_test_gbr_reg)
error_score_MSE = metrics.mean_squared_error(y_test, test_data_prediction_X_test_gbr_reg)
print("R squared Error : ", error_score_r2)
print("mean_absolute_error : ", error_score_MAE)
print("mean_squared_error : ", error_score_MSE)
print("RMSE",np.sqrt(mean_squared_error(y_test,test_data_prediction_X_test_gbr_reg)))

R squared Error :  0.999999626717236
mean_absolute_error :  0.020996227149000513
mean_squared_error :  0.0006527291778554793
RMSE 0.025548565084080148
R squared Error :  0.822576302652973
mean_absolute_error :  9.640214457388888
mean_squared_error :  125.61658206286775
RMSE 11.207880355485052


In [10]:
# can tune other metrics, such as MSE
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
scaler = MinMaxScaler()
# fit the scaler to the train set, it will learn the parameters
scaler.fit(X)
# transform train and test sets
X_scaled_MM = scaler.transform(X)
X_scaled_MM = pd.DataFrame(X_scaled_MM, columns=X.columns)

scores = cross_val_score(gbr_reg_model, X_scaled_MM, y, cv=2)
print(scores)
print(np.mean(scores))

scores = cross_val_score(gbr_reg_model, X_scaled_MM, y, cv=3)
print(scores)
print(np.mean(scores))

scores = cross_val_score(gbr_reg_model, X_scaled_MM, y, cv=4)
print(scores)
print(np.mean(scores))

scores = cross_val_score(gbr_reg_model, X_scaled_MM, y, cv=5)
print(scores)
print(np.mean(scores))


[0.85151238 0.81970247]
0.8356074236564002
[0.87484638 0.87492055 0.65681849]
0.8021951401300423
[0.81096859 0.81445845 0.94912277 0.58417622]
0.7896815083314677
[0.69885056 0.94392191 0.53129109 0.95996981 0.39560872]
0.7059284181505273


In [13]:

# Initialize the Leave-One-Out cross-validator
loo = LeaveOneOut()

X = df_3.drop(['T04','F01','F02','F04','F06','F04','F05','F09','F07','F10',],axis=1)
y = df_3['T04']# loading the linear regression model


# Apply MinMax Scaling
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)  # Scale the features and store them in X_scaled


# Initialize lists to store predictions and actual values
y_pred_loo = []
y_true_loo = []

# Loop over each training/test split
for train_index, test_index in loo.split(X_scaled):
    X_train_loo, X_test_loo = X_scaled[train_index], X_scaled[test_index]
    y_train_loo, y_test_loo = y.iloc[train_index], y.iloc[test_index]
    
    # Train the Lasso model
gb_reg_model = GradientBoostingRegressor(
    n_estimators=best_params['n_estimators'],
    learning_rate=best_params['learning_rate'],
    min_samples_split=best_params['min_samples_split'],
    min_samples_leaf=best_params['min_samples_leaf'],
    subsample=best_params['subsample'],
    max_features=best_params['max_features']
)

gb_reg_model.fit(X_train_loo, y_train_loo)
    
# Predict the left-out sample
y_pred_loo.append(gb_reg_model.predict(X_test_loo)[0])
y_true_loo.append(y_test_loo.values[0])

# Convert lists to arrays
y_pred_loo = np.array(y_pred_loo)
y_true_loo = np.array(y_true_loo)

# Calculate LOO performance metrics
Q2_loo = r2_score(y_true_loo, y_pred_loo)
MAE_loo = mean_absolute_error(y_true_loo, y_pred_loo)
MSE_loo = mean_squared_error(y_true_loo, y_pred_loo)
RMSE_loo = np.sqrt(MSE_loo)

# Print the results
print("LOO Q^2 score: ", Q2_loo)
print("LOO Mean Absolute Error: ", MAE_loo)
print("LOO Mean Squared Error: ", MSE_loo)
print("LOO Root Mean Squared Error: ", RMSE_loo)



LOO Q^2 score:  nan
LOO Mean Absolute Error:  10.677047599347844
LOO Mean Squared Error:  113.99934543873957
LOO Root Mean Squared Error:  10.677047599347844


c:\users\nettemchandra sekhar\appdata\local\programs\python\python39\lib\site-packages\sklearn\metrics\_regression.py:918: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
