In [1]:
from sklearn.model_selection import GridSearchCV
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
import shap
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.model_selection import GridSearchCV
from sklearn import metrics
import scipy.stats as stat
import pylab 
import math
from sklearn.neighbors import KNeighborsClassifier as knn
from sklearn.linear_model import LogisticRegression as LGR,Lasso
from sklearn.ensemble import RandomForestClassifier as rfc
from sklearn.feature_selection import SelectFromModel
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import StratifiedKFold
from sklearn.ensemble import RandomForestRegressor
import xgboost as xgb
import xgboost as xgb
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.neighbors import KNeighborsRegressor

c:\users\nettemchandra sekhar\appdata\local\programs\python\python39\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
Fe_CAAC_dataset = df = pd.read_excel("F:\\Nitrogen_activation\\rajaraman\\office\\ofifice\\jupyter\\Extension\\T07\\heatmap\\agostic\\xgboost\\N2_activation_extension_T07_heatmap_agostaic_descrptors.xlsx")

In [3]:
df_1=df.drop(['F00','T01','T02','T03',],axis=1)
df_2=df_1.drop([0,18,9])
df_3=df_1.drop([0,18,9,8,26,17])
df_4=df_1.drop([8,26,17])

In [4]:
X = df_3.drop(['T04','F01','F02','F04','F06','F04','F05','F09','F07','F10',],axis=1)
y = df_3['T04']# loading the linear regression model


X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20, random_state=10)

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
scaler = MinMaxScaler()
# fit the scaler to the train set, it will learn the parameters
scaler.fit(X_train)
# transform train and test sets
X_train_scaled_MM = scaler.transform(X_train)
X_test_scaled_MM = scaler.transform(X_test)
X_train_scaled_MM = pd.DataFrame(X_train_scaled_MM, columns=X_train.columns)
X_test_scaled_MM = pd.DataFrame(X_test_scaled_MM, columns=X_test.columns)

# Define the parameter grid
param_grid = {
    'n_neighbors': [3, 5, 7, 10],
    'weights': ['uniform', 'distance'],
    'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
    'p': [1, 2]  # p=1 for Manhattan distance, p=2 for Euclidean distance
}

knn_reg_model= KNeighborsRegressor()


# Set up Grid Search
grid_search = GridSearchCV(
    estimator=knn_reg_model,
    param_grid=param_grid,
    cv=5,
    scoring='neg_mean_squared_error',
    n_jobs=-1,
    verbose=2
)


# Fit the model
grid_search.fit(X_train_scaled_MM, y_train)


#print("Best parameters found: ", grid_search.best_params_)
print("Best score: ", grid_search.best_score_)
best_params = grid_search.best_params_
print("Best parameters found: ", best_params)

Fitting 5 folds for each of 64 candidates, totalling 320 fits
Best score:  -525.6232387662592
Best parameters found:  {'algorithm': 'auto', 'n_neighbors': 3, 'p': 1, 'weights': 'distance'}


In [5]:
# Initialize KNeighborsRegressor with the best parameters
knn_reg_model = KNeighborsRegressor(
    n_neighbors=best_params['n_neighbors'],
    weights=best_params['weights'],
    algorithm=best_params['algorithm'],
    p=best_params['p']
)

knn_reg_model.fit(X_train_scaled_MM,y_train)

# prediction on Training data
training_data_prediction_X_train_knn_reg = knn_reg_model.predict(X_train_scaled_MM)
# prediction on Test data
test_data_prediction_X_test_knn_reg = knn_reg_model.predict(X_test_scaled_MM)
error_score_r2 = metrics.r2_score(y_train, training_data_prediction_X_train_knn_reg)
error_score_MAE = metrics.mean_absolute_error(y_train, training_data_prediction_X_train_knn_reg)
error_score_MSE = metrics.mean_squared_error(y_train, training_data_prediction_X_train_knn_reg)
print("R squared Error : ", error_score_r2)
print("mean_absolute_error : ", error_score_MAE)
print("mean_squared_error : ", error_score_MSE)
print("RMSE",np.sqrt(mean_squared_error(y_train,training_data_prediction_X_train_knn_reg)))
# R squared Error
error_score_r2 = metrics.r2_score(y_test, test_data_prediction_X_test_knn_reg)
error_score_MAE = metrics.mean_absolute_error(y_test, test_data_prediction_X_test_knn_reg)
error_score_MSE = metrics.mean_squared_error(y_test, test_data_prediction_X_test_knn_reg)
print("R squared Error : ", error_score_r2)
print("mean_absolute_error : ", error_score_MAE)
print("mean_squared_error : ", error_score_MSE)
print("RMSE",np.sqrt(mean_squared_error(y_test,test_data_prediction_X_test_knn_reg)))

R squared Error :  1.0
mean_absolute_error :  0.0
mean_squared_error :  0.0
RMSE 0.0
R squared Error :  0.7115880225791256
mean_absolute_error :  12.734042505201987
mean_squared_error :  246.0258356557848
RMSE 15.6852107303595


In [6]:
# Initialize KNeighborsRegressor with the best parameters
knn_reg_model = KNeighborsRegressor(algorithm='auto',n_neighbors=2, p=1, weights='uniform')

knn_reg_model.fit(X_train_scaled_MM,y_train)

# prediction on Training data
training_data_prediction_X_train_knn_reg = knn_reg_model.predict(X_train_scaled_MM)
# prediction on Test data
test_data_prediction_X_test_knn_reg = knn_reg_model.predict(X_test_scaled_MM)
error_score_r2 = metrics.r2_score(y_train, training_data_prediction_X_train_knn_reg)
error_score_MAE = metrics.mean_absolute_error(y_train, training_data_prediction_X_train_knn_reg)
error_score_MSE = metrics.mean_squared_error(y_train, training_data_prediction_X_train_knn_reg)
print("R squared Error : ", error_score_r2)
print("mean_absolute_error : ", error_score_MAE)
print("mean_squared_error : ", error_score_MSE)
print("RMSE",np.sqrt(mean_squared_error(y_train,training_data_prediction_X_train_knn_reg)))
# R squared Error
error_score_r2 = metrics.r2_score(y_test, test_data_prediction_X_test_knn_reg)
error_score_MAE = metrics.mean_absolute_error(y_test, test_data_prediction_X_test_knn_reg)
error_score_MSE = metrics.mean_squared_error(y_test, test_data_prediction_X_test_knn_reg)
print("R squared Error : ", error_score_r2)
print("mean_absolute_error : ", error_score_MAE)
print("mean_squared_error : ", error_score_MSE)
print("RMSE",np.sqrt(mean_squared_error(y_test,test_data_prediction_X_test_knn_reg)))

R squared Error :  0.9170870373176699
mean_absolute_error :  8.332917248227417
mean_squared_error :  130.37756170003308
RMSE 11.418299422419834
R squared Error :  0.9004022076152798
mean_absolute_error :  8.823772259771502
mean_squared_error :  84.96051488584486
RMSE 9.217402827578105


In [7]:
# can tune other metrics, such as MSE
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
scaler = MinMaxScaler()
# fit the scaler to the train set, it will learn the parameters
scaler.fit(X)
# transform train and test sets
X_scaled_MM = scaler.transform(X)
X_scaled_MM = pd.DataFrame(X_scaled_MM, columns=X.columns)

scores = cross_val_score(knn_reg_model, X_scaled_MM, y, cv=2)
print(scores)
print(np.mean(scores))

scores = cross_val_score(knn_reg_model, X_scaled_MM, y, cv=3)
print(scores)
print(np.mean(scores))

scores = cross_val_score(knn_reg_model, X_scaled_MM, y, cv=4)
print(scores)
print(np.mean(scores))

scores = cross_val_score(knn_reg_model, X_scaled_MM, y, cv=5)
print(scores)
print(np.mean(scores))



[0.79326434 0.73450617]
0.7638852521348177
[0.90075352 0.79159783 0.75869041]
0.8170139209013421
[0.81856777 0.74305472 0.9578439  0.67583243]
0.7988247039742316
[0.71304312 0.90744488 0.34527324 0.93392899 0.55703621]
0.6913452885634438


In [8]:

# Initialize the Leave-One-Out cross-validator
loo = LeaveOneOut()

X = df_3.drop(['T04','F01','F02','F04','F06','F04','F05','F09','F07','F10',],axis=1)
y = df_3['T04']# loading the linear regression model


# Apply MinMax Scaling
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)  # Scale the features and store them in X_scaled


# Initialize lists to store predictions and actual values
y_pred_loo = []
y_true_loo = []

# Loop over each training/test split
for train_index, test_index in loo.split(X_scaled):
    X_train_loo, X_test_loo = X_scaled[train_index], X_scaled[test_index]
    y_train_loo, y_test_loo = y.iloc[train_index], y.iloc[test_index]
    
    # Train the Lasso model
knn_reg_model = KNeighborsRegressor(algorithm='auto',n_neighbors=2, p=1, weights='uniform')
knn_reg_model.fit(X_train_loo, y_train_loo)
    
# Predict the left-out sample
y_pred_loo.append(knn_reg_model.predict(X_test_loo)[0])
y_true_loo.append(y_test_loo.values[0])

# Convert lists to arrays
y_pred_loo = np.array(y_pred_loo)
y_true_loo = np.array(y_true_loo)

# Calculate LOO performance metrics
Q2_loo = r2_score(y_true_loo, y_pred_loo)
MAE_loo = mean_absolute_error(y_true_loo, y_pred_loo)
MSE_loo = mean_squared_error(y_true_loo, y_pred_loo)
RMSE_loo = np.sqrt(MSE_loo)

# Print the results
print("LOO Q^2 score: ", Q2_loo)
print("LOO Mean Absolute Error: ", MAE_loo)
print("LOO Mean Squared Error: ", MSE_loo)
print("LOO Root Mean Squared Error: ", RMSE_loo)



LOO Q^2 score:  nan
LOO Mean Absolute Error:  11.954177177535712
LOO Mean Squared Error:  142.90235199191568
LOO Root Mean Squared Error:  11.954177177535712


c:\users\nettemchandra sekhar\appdata\local\programs\python\python39\lib\site-packages\sklearn\metrics\_regression.py:918: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
