In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.model_selection import GridSearchCV
from sklearn import metrics
import scipy.stats as stat
import pylab 
import math
from sklearn.neighbors import KNeighborsClassifier as knn
from sklearn.linear_model import LogisticRegression as LGR,Lasso
from sklearn.ensemble import RandomForestClassifier as rfc
from sklearn.feature_selection import SelectFromModel
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import StratifiedKFold

In [2]:
Fe_CAAC_dataset = df = pd.read_excel("F:\\Nitrogen_activation\\rajaraman\\office\\ofifice\\jupyter\\Extension\\T07\\heatmap\\agostic\\Lasso\\N2_activation_extension_T07_heatmap_agostaic_descrptors.xlsx")

In [3]:
df_1=df.drop(['F00','T01','T02','T03',],axis=1)
df_2=df_1.drop([0,18,9])
df_3=df_1.drop([0,18,9,8,26,17])
df_4=df_1.drop([8,26,17])

In [4]:
X = df_3.drop(['T04','F01','F02','F04','F06','F04','F05','F09','F07','F10',],axis=1)
y = df_3['T04']# loading the linear regression model


X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20, random_state=20)
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
scaler = MinMaxScaler()
# fit the scaler to the train set, it will learn the parameters
scaler.fit(X_train)
# transform train and test sets
X_train_scaled_MM = scaler.transform(X_train)
X_test_scaled_MM = scaler.transform(X_test)
X_train_scaled_MM = pd.DataFrame(X_train_scaled_MM, columns=X_train.columns)
X_test_scaled_MM = pd.DataFrame(X_test_scaled_MM, columns=X_test.columns)

# Define the parameter grid
param_grid = {'alpha': np.logspace(-4, 4, 50)}

# Above one Range of Alpha Values: The alpha values will range from 0.0001 to 100.
#Above  oneNumber of Alphas: 100 different alpha values will be considered.

# Initialize a Lasso model
lasso = Lasso()

# Use GridSearchCV to find the best alpha
grid_search = GridSearchCV(lasso, param_grid, cv=5, scoring='neg_mean_squared_error', n_jobs=-1)
grid_search.fit(X_train_scaled_MM, y_train)

# Best alpha value found by GridSearchCV
best_alpha = grid_search.best_params_['alpha']
print(f"Best alpha value found by GridSearchCV: {best_alpha}")

Best alpha value found by GridSearchCV: 0.12648552168552957


In [5]:
X = df_3.drop(['T04','F01','F02','F04','F06','F04','F05','F09','F07','F10',],axis=1)
y = df_3['T04']# loading the linear regression model


X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20, random_state=20)
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
scaler = MinMaxScaler()
# fit the scaler to the train set, it will learn the parameters
scaler.fit(X_train)
# transform train and test sets
X_train_scaled_MM = scaler.transform(X_train)
X_test_scaled_MM = scaler.transform(X_test)
X_train_scaled_MM = pd.DataFrame(X_train_scaled_MM, columns=X_train.columns)
X_test_scaled_MM = pd.DataFrame(X_test_scaled_MM, columns=X_test.columns)

#LassoRegression_scaling_MM
lasso_reg_model = Lasso(alpha=0.126)
lasso_reg_model.fit(X_train_scaled_MM,y_train)
# prediction on Training data
training_data_prediction_X_train_lasso_reg = lasso_reg_model.predict(X_train_scaled_MM)
# prediction on Test data
test_data_prediction_X_test_lasso_reg = lasso_reg_model.predict(X_test_scaled_MM)

# R squared Error
error_score_r2 = metrics.r2_score(y_train, training_data_prediction_X_train_lasso_reg)
error_score_MAE = metrics.mean_absolute_error(y_train, training_data_prediction_X_train_lasso_reg)
error_score_MSE = metrics.mean_squared_error(y_train, training_data_prediction_X_train_lasso_reg)
print("R squared Error : ", error_score_r2)
print("mean_absolute_error : ", error_score_MAE)
print("mean_squared_error : ", error_score_MSE)
print("RMSE",np.sqrt(mean_squared_error(y_train,training_data_prediction_X_train_lasso_reg)))
# R squared Error
error_score_r2 = metrics.r2_score(y_test, test_data_prediction_X_test_lasso_reg)
error_score_MAE = metrics.mean_absolute_error(y_test, test_data_prediction_X_test_lasso_reg)
error_score_MSE = metrics.mean_squared_error(y_test, test_data_prediction_X_test_lasso_reg)
print("R squared Error : ", error_score_r2)
print("mean_absolute_error : ", error_score_MAE)
print("mean_squared_error : ", error_score_MSE)
print("RMSE",np.sqrt(mean_squared_error(y_test,test_data_prediction_X_test_lasso_reg)))
coeff = lasso_reg_model.coef_
features = X_train_scaled_MM.columns
df_coeff = pd.DataFrame({"features":features,"coeff":coeff})
df_coeff.sort_values("coeff")


R squared Error :  0.9186068606131069
mean_absolute_error :  8.87151460347344
mean_squared_error :  142.32555606364429
RMSE 11.930027496349046
R squared Error :  0.8105228068680318
mean_absolute_error :  10.404105020186174
mean_squared_error :  134.1504981352625
RMSE 11.582335607953281


features       coeff
0      F03 -122.210278
1      F08   34.284573

In [6]:
scores = cross_val_score(lasso_reg_model, X_train, y_train, cv=2)
print(scores)
print(np.mean(scores))
# can tune other metrics, such as MSE
scores = cross_val_score(lasso_reg_model, X, y, cv=3)
print(scores)
print(np.mean(scores))

scores = cross_val_score(lasso_reg_model, X, y, cv=4)
print(scores)
print(np.mean(scores))

scores = cross_val_score(lasso_reg_model, X, y, cv=5)
print(scores)
print(np.mean(scores))

coeff = lasso_reg_model.coef_

features = X_train.columns
features = X_train.columns
df_coeff = pd.DataFrame({"features":features,"coeff":coeff})
df_coeff.sort_values("coeff")

[0.85098512 0.89257566]
0.8717803884973734
[0.89324576 0.86774026 0.87308128]
0.8780224359348013
[0.79993887 0.85565816 0.94660062 0.82341621]
0.8564034660471469
[0.67784629 0.9311903  0.72127233 0.95371703 0.73766165]
0.8043375175975921


features       coeff
0      F03 -122.210278
1      F08   34.284573

In [7]:

# Initialize the Leave-One-Out cross-validator
loo = LeaveOneOut()

X = df_3.drop(['T04','F01','F02','F04','F06','F04','F05','F09','F07','F10',],axis=1)
y = df_3['T04']# loading the linear regression model

# Apply MinMax Scaling
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)  # Scale the features and store them in X_scaled


# Initialize lists to store predictions and actual values
y_pred_loo = []
y_true_loo = []

# Loop over each training/test split
for train_index, test_index in loo.split(X_scaled):
    X_train_loo, X_test_loo = X_scaled[train_index], X_scaled[test_index]
    y_train_loo, y_test_loo = y.iloc[train_index], y.iloc[test_index]
    
    # Train the Lasso model
    lasso_reg_model = Lasso(alpha=0.12)
    lasso_reg_model.fit(X_train_loo, y_train_loo)
    
    # Predict the left-out sample
    y_pred_loo.append(lasso_reg_model.predict(X_test_loo)[0])
    y_true_loo.append(y_test_loo.values[0])

# Convert lists to arrays
y_pred_loo = np.array(y_pred_loo)
y_true_loo = np.array(y_true_loo)

# Calculate LOO performance metrics
Q2_loo = r2_score(y_true_loo, y_pred_loo)
MAE_loo = mean_absolute_error(y_true_loo, y_pred_loo)
MSE_loo = mean_squared_error(y_true_loo, y_pred_loo)
RMSE_loo = np.sqrt(MSE_loo)

# Print the results
print("LOO Q^2 score: ", Q2_loo)
print("LOO Mean Absolute Error: ", MAE_loo)
print("LOO Mean Squared Error: ", MSE_loo)
print("LOO Root Mean Squared Error: ", RMSE_loo)



LOO Q^2 score:  0.8712743867472289
LOO Mean Absolute Error:  10.728701334473262
LOO Mean Squared Error:  193.20129740904468
LOO Root Mean Squared Error:  13.899686953634772


In [8]:
comparison_df_train_lasso = pd.DataFrame({'Actual Barrier (kJ/mol)': y_train, 'Predicted Barrier (kJ/mol)': training_data_prediction_X_train_lasso_reg})

comparison_df_train_lasso.to_excel('predicted_vs_actual_comparison_train_lasso.xlsx', index=False)

comparison_df_test_lasso = pd.DataFrame({'Actual Barrier (kJ/mol)': y_test, 'Predicted Barrier (kJ/mol)': test_data_prediction_X_test_lasso_reg})

comparison_df_test_lasso.to_excel('predicted_vs_actual_comparison_test_lasso.xlsx', index=False)

print(comparison_df_train_lasso)

print(comparison_df_test_lasso)

    Actual Barrier (kJ/mol)  Predicted Barrier (kJ/mol)
15               134.989547                  133.857885
16               172.156151                  162.620533
22                60.127639                   84.939484
19                48.921745                   49.113560
25               153.204294                  157.231805
13               111.384753                   88.336984
6                126.165031                  132.430294
11                84.663254                   69.607346
7                158.160792                  160.845748
1                 25.243201                   48.900898
3                 63.400511                   66.946512
10                54.848496                   48.726322
14                96.725090                  102.512119
12                77.707753                   75.940754
20                70.614886                   63.426283
4                 97.057793                   89.934411
    Actual Barrier (kJ/mol)  Predicted Barrier (